import "server-only";

/* eslint-disable @typescript-eslint/no-unused-vars -- protected secrets are intentionally removed with rest destructuring */

import { createHash, randomUUID } from "node:crypto";

import type { AdminCommand, AdminDashboardView, AdminListQuery, AdminRecordView, AdminSectionId, AdminSectionView, ContentDraftInput, ContentKind } from "@/lib/admin";
import type { AuthenticatedPrincipal } from "@/lib/auth";
import { ApplicationError, createTransactionalEventServices, PrismaTransactionRunner } from "@/lib/application";
import type { AesGcmDataProtector } from "@/lib/data-protection";
import { Prisma, type DatabaseClient, type PrismaClient } from "@/lib/db";
import { assertTransition, supportStateMachine } from "@/lib/domain";
import { PrismaAdminRepository } from "@/lib/repositories";
import { createProductNotification } from "./product-notification";
import { promocodeFingerprint } from "./platform-operations-service";

const encoder = new TextEncoder();
const contentSections: readonly AdminSectionId[] = ["opportunities", "tasks", "content", "rewards"];
const uuidPattern = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const idempotencyPattern = /^[A-Za-z0-9_.:-]{8,160}$/;

function requirePermission(actor: AuthenticatedPrincipal, permission: string) {
  if (!actor.roleKeys.includes("admin") || !actor.permissionKeys.includes(permission)) throw new ApplicationError("FORBIDDEN", "Недостаточно прав для административной операции");
}
function clean(value: unknown, min: number, max: number, label: string) { const output = typeof value === "string" ? value.trim() : ""; if (output.length < min || output.length > max) throw new ApplicationError("VALIDATION", `${label}: допустимо от ${min} до ${max} символов`); return output; }
function key(value: string | undefined, title: string) { const normalized = (value || title).toLowerCase().replace(/[^a-z0-9а-яё]+/gi, "-").replace(/^-|-$/g, "").slice(0, 100); if (normalized.length < 3) throw new ApplicationError("VALIDATION", "Укажите корректный ключ контента"); return normalized; }
function iso(value: Date | null | undefined) { return value?.toISOString() ?? "Не указано"; }
function fields(...values: Array<[string, unknown, string?]>) { return values.map(([label, value, help]) => ({ label, value: value === null || value === undefined || value === "" ? "Не указано" : String(value), help })); }
function page<T extends { id: string }>(rows: T[], map: (row: T) => AdminRecordView, requested = 30): AdminSectionView { const hasNext = rows.length > requested; const visible = hasNext ? rows.slice(0, requested) : rows; return { items: visible.map(map), total: visible.length, nextCursor: hasNext ? visible.at(-1)!.id : null }; }
function asJson(value: object): Prisma.InputJsonValue { return value as Prisma.InputJsonValue; }

export class AdminApplicationService {
  private readonly transactions: PrismaTransactionRunner;
  constructor(private readonly database: PrismaClient, private readonly protector: AesGcmDataProtector) { this.transactions = new PrismaTransactionRunner(database); }

  async dashboard(actor: AuthenticatedPrincipal): Promise<AdminDashboardView> {
    requirePermission(actor, "admin.dashboard.read");
    const since = new Date(); since.setUTCHours(0, 0, 0, 0);
    return { ...(await new PrismaAdminRepository(this.database).dashboard(since)), calculatedAt: new Date().toISOString() };
  }

  async list(actor: AuthenticatedPrincipal, section: AdminSectionId, query: AdminListQuery = {}): Promise<AdminSectionView> {
    requirePermission(actor, this.readPermission(section));
    const repository = new PrismaAdminRepository(this.database); const limit = Math.min(Math.max(query.take ?? 30, 1), 100);
    switch (section) {
      case "users": return page(await repository.list(section, query), (item) => ({ id: item.id, eyebrow: item.profile?.productRole === "PARTNER" ? "Партнёр" : "Игрок", title: item.displayName || item.email, description: item.email, status: item.profile?.accountStatus ?? "Профиль не создан", nextStep: item.profile?.partnerProfile?.status === "PENDING" ? "Требуется решение по партнёрскому доступу" : "Проверить профиль и историю статусов", fields: fields(["Роль", item.profile?.productRole], ["Рынок", item.profile?.market.name], ["Создан", iso(item.createdAt)]), tags: item.adminTagAssignments.map(({ tag }: { tag: { id: string; name: string } }) => ({ id: tag.id, name: tag.name })) }), limit);
      case "services": return page(await repository.list(section, query), (item) => ({ id: item.id, eyebrow: "Партнёрский сервис", title: item.name, description: item.key, status: item.status, nextStep: item.status === "DRAFT" ? "Подготовить условия по рынкам" : "Проверить доступность", fields: fields(["Рынки", item.markets.map((entry: { market: { code: string } }) => entry.market.code).join(", ")], ["Обновлён", iso(item.updatedAt)]) }), limit);
      case "opportunities": return page(await repository.list(section, query), (item) => ({ id: item.id, eyebrow: item.type, title: item.title, description: item.description, status: item.status, nextStep: item.nextStep, fields: fields(["Ключ", item.key], ["Сегменты", item.audiences.map((entry: { productRole: string; market: { code: string } }) => `${entry.productRole}/${entry.market.code}`).join(", ")], ["Опубликовано", iso(item.publishedAt)]) }), limit);
      case "tasks": return page(await repository.list(section, query), (item) => { const version = item.versions[0]; return { id: item.id, eyebrow: `Задание · ${version ? `версия ${version.version}` : "без версии"}`, title: version?.title ?? item.key, description: version?.summary ?? "Версия задания ещё не создана.", status: version?.status ?? "DRAFT", nextStep: version?.status === "PUBLISHED" ? "Контролировать очередь результатов" : "Подготовить и опубликовать версию", fields: fields(["Принято пользователями", item._count.userTasks], ["Инструкция", version?.instructionVersion?.title], ["Сегменты", version?.audiences.map((entry: { productRole: string; market: { code: string } }) => `${entry.productRole}/${entry.market.code}`).join(", ")]) }; }, limit);
      case "reviews": return page(await repository.list(section, query), (item) => { const task = item.taskSubmission.userTask; return { id: item.id, eyebrow: `Результат · версия ${item.version}`, title: task.taskVersion.title, description: `Пользователь: ${task.user.displayName || task.user.email}`, status: task.status, nextStep: item.reviews.length ? "Решение сохранено в истории" : "Принять объяснимое решение", fields: fields(["Рынок", task.user.profile?.market.name], ["Роль", task.user.profile?.productRole], ["Отправлено", iso(item.submittedAt)], ["Решений", item.reviews.length]) }; }, limit);
      case "rewards": { const definitions = await repository.listRewardTypes(query); const definitionRecords: AdminRecordView[] = definitions.map((item) => ({ id: item.id, eyebrow: "Тип VX Reward", title: item.name, description: item.description, status: item.status, nextStep: item.status === "PUBLISHED" ? "Используется серверным каталогом" : "Подготовить публикацию", editable: true, fields: fields(["Ключ", item.key], ["Вид", item.valueKind], ["Создано Rewards", item._count.rewards]) })); const instances = await repository.list(section, query); const instanceRecords: AdminRecordView[] = instances.map((item) => ({ id: item.id, eyebrow: item.rewardType.name, title: item.title, description: item.description, status: item.status, nextStep: "Проверить основание и историю статусов", editable: false, fields: fields(["Пользователь", item.user.displayName || item.user.email], ["Роль", item.user.profile?.productRole], ["Рынок", item.user.profile?.market.name], ["Создан", iso(item.createdAt)]) })); return { items: [...definitionRecords, ...instanceRecords].slice(0, limit), total: Math.min(definitionRecords.length + instanceRecords.length, limit), nextCursor: null }; }
      case "economy": return page(await repository.list(section, query), (item) => ({ id: item.id, eyebrow: "VX Points · append-only", title: `${item.delta > 0 ? "+" : ""}${item.delta} VX Points`, description: item.reason, status: item.status, nextStep: item.status === "CONFIRMED" ? "Запись учтена сервером" : "Проверить состояние записи", fields: fields(["Пользователь", item.user.displayName || item.user.email], ["Источник", `${item.sourceType}:${item.sourceId}`], ["Время", iso(item.occurredAt)]) }), limit);
      case "support": return page(await repository.list(section, query), (item) => ({ id: item.id, eyebrow: item.categoryDefinition.title, title: item.subject, description: item.user.displayName || item.user.email, status: item.status, nextStep: item.assignedTo ? `Назначено: ${item.assignedTo.displayName || item.assignedTo.email}` : "Назначить оператора", fields: fields(["Приоритет", item.priority], ["Сообщений", item._count.messages], ["Внутренних заметок", item._count.internalNotes], ["Апелляций", item.appeals.length]) }), limit);
      case "content": { const editorial = await repository.listEditorialContent(query); const records: AdminRecordView[] = [
        ...editorial.instructions.map((item) => { const version = item.versions[0]; return { id: item.id, eyebrow: `Инструкция · ${version ? `версия ${version.version}` : "без версии"}`, title: version?.title ?? item.title, description: version?.summary ?? "Версия инструкции ещё не создана.", status: version?.status ?? "DRAFT", nextStep: version?.status === "PUBLISHED" ? "Проверить актуальность" : "Подготовить публикацию", fields: fields(["Ключ", item.key], ["Язык", version?.language], ["Шагов", version?.steps.length], ["Сегментов", version?.audiences.length]) }; }),
        ...editorial.forecasts.map((item) => { const version = item.versions[0]; const summary = version?.content && typeof version.content === "object" && !Array.isArray(version.content) ? String((version.content as Record<string, unknown>).summary ?? "") : ""; return { id: item.id, eyebrow: `Прогноз · ${version ? `версия ${version.version}` : "без версии"}`, title: item.title, description: summary || "Версия прогноза ещё не создана.", status: version?.status ?? "DRAFT", nextStep: version?.status === "PUBLISHED" ? "Проверить срок актуальности" : "Подготовить публикацию", fields: fields(["Ключ", item.key], ["Автор", item.author.displayName || item.author.email], ["Действует до", iso(version?.validUntil)], ["Правил доступа", version?.accessRules.length]) }; }),
        ...editorial.promocodes.map((item) => ({ id: item.id, eyebrow: "Промокод", title: `${item.partnerService.name} · ${item.key}`, description: item.instructions, status: item.status, nextStep: item.status === "PUBLISHED" ? "Контролировать срок и активации" : "Подготовить публикацию", fields: fields(["Роль", item.productRole], ["Рынок", item.market.name], ["Действует до", iso(item.validUntil)], ["Активаций", item.activations.length]) })),
      ]; return { items: records.slice(0, limit), total: Math.min(records.length, limit), nextCursor: null }; }
      case "notifications": return page(await repository.list(section, query), (item) => ({ id: item.id, eyebrow: item.type, title: item.title, description: item.body, status: item.status, nextStep: item.status === "READ" ? "Прочитано пользователем" : "Доставка сохранена в истории", fields: fields(["Получатель", item.user.displayName || item.user.email], ["Пакет", item.batch?.id], ["Отправлено", iso(item.sentAt)]) }), limit);
      case "team": return page(await repository.list(section, query), (item) => ({ id: item.id, eyebrow: "Инфраструктурная роль", title: item.name, description: item.description ?? "Без описания", status: `${item.permissions.length} разрешений`, nextStep: "Проверить принцип минимальных полномочий", fields: fields(["Ключ", item.key], ["Сотрудников", item._count.users], ["Разрешения", item.permissions.map((entry: { key: string }) => entry.key).join(", ")]) }), limit);
      case "audit": return page(await repository.list(section, query), (item) => ({ id: item.id, eyebrow: item.actorType, title: item.action, description: `${item.targetType}${item.targetId ? ` · ${item.targetId}` : ""}`, status: "Неизменяемая запись", nextStep: "Только просмотр", fields: fields(["Автор", item.actorId], ["Сессия", item.actorSessionId], ["Время", iso(item.occurredAt)], ["Метаданные", JSON.stringify(item.metadata)]) }), limit);
      case "settings": return page(await repository.list(section, query), (item) => ({ id: item.id, eyebrow: "Рынок", title: item.name, description: `Код: ${item.code}`, status: item.isActive ? "ACTIVE" : "INACTIVE", nextStep: "Системные изменения выполняются отдельным защищённым процессом", fields: fields(["Язык", item.defaultLanguage], ["Обновлён", iso(item.updatedAt)]) }), limit);
    }
  }

  async get(actor: AuthenticatedPrincipal, section: AdminSectionId, id: string): Promise<AdminRecordView> {
    const result = await this.list(actor, section, { take: 100 }); const fromPage = result.items.find((item) => item.id === id); if (fromPage) return fromPage;
    requirePermission(actor, this.readPermission(section));
    if (contentSections.includes(section)) { const repository = new PrismaAdminRepository(this.database); const revision = section === "content" ? await repository.latestContentRevision(id) : await repository.latestRevision(this.sectionKind(section), id); if (revision) { const snapshot = revision.snapshot && typeof revision.snapshot === "object" && !Array.isArray(revision.snapshot) ? revision.snapshot as Record<string, unknown> : {}; const label = revision.entityType === "FORECAST" ? "Прогноз" : revision.entityType === "PROMOCODE" ? "Промокод" : revision.entityType; return { id, eyebrow: `${label} · версия ${revision.version}`, title: String(snapshot.title ?? "Контент VX House"), description: String(snapshot.description ?? ""), status: revision.status, nextStep: revision.status === "PUBLISHED" ? "Проверить актуальность" : "Подготовить публикацию", editable: true, fields: fields(["Версия", revision.version], ["Основание", revision.reason], ["Создано", iso(revision.createdAt)]) }; } }
    const item = await new PrismaAdminRepository(this.database).find(section, id); if (!item) throw new ApplicationError("NOT_FOUND", "Запись не найдена");
    return { id, eyebrow: "Серверная запись", title: "Запись VX House", description: "Запись существует, но не входит в текущую страницу списка.", status: "Доступна", nextStep: "Открыть через отфильтрованный список", fields: fields(["Идентификатор", id]) };
  }

  execute(actor: AuthenticatedPrincipal, section: AdminSectionId, id: string, command: AdminCommand) {
    switch (command.action) {
      case "USER_STATUS": return this.changeUserStatus(actor, id, command.status, command.reason);
      case "USER_ROLE": return this.changeUserRole(actor, id, command.role, command.reason);
      case "PARTNER_APPROVAL": return this.approvePartner(actor, id, command.status, command.reason);
      case "CONTENT_DRAFT": return this.createContentRevision(actor, command.content, id === "new" ? undefined : id);
      case "CONTENT_PUBLISH": return this.changeContentPublication(actor, section, id, "PUBLISHED", command.reason);
      case "CONTENT_ARCHIVE": return this.changeContentPublication(actor, section, id, "ARCHIVED", command.reason);
      case "MODERATION_DECISION": return this.moderate(actor, id, command);
      case "SUPPORT_ASSIGN": return this.assignSupport(actor, id, command.operatorId, command.reason);
      case "SUPPORT_REPLY": return this.addSupportText(actor, id, command.body, "REPLY");
      case "SUPPORT_NOTE": return this.addSupportText(actor, id, command.body, "NOTE");
      case "SUPPORT_STATUS": return this.transitionSupport(actor, id, command.status, command.reason);
      case "APPEAL_DECISION": return this.decideAppeal(actor, command.appealId, command.status, command.reason);
      case "ECONOMY_ADJUST": return this.adjustEconomy(actor, command);
      case "NOTIFY": return this.sendNotifications(actor, command);
    }
    throw new ApplicationError("VALIDATION", "Неизвестная административная команда");
  }

  create(actor: AuthenticatedPrincipal, section: AdminSectionId, command: AdminCommand) {
    if (command.action === "CONTENT_DRAFT" && contentSections.includes(section)) return this.createContentRevision(actor, command.content);
    if (command.action === "NOTIFY" && section === "notifications") return this.sendNotifications(actor, command);
    throw new ApplicationError("VALIDATION", "Создание недоступно для выбранного раздела");
  }

  private readPermission(section: AdminSectionId) { if (section === "users") return "users.read"; if (["opportunities", "tasks", "content", "rewards", "services"].includes(section)) return "content.read"; if (section === "reviews") return "moderation.read"; if (section === "support") return "support.admin"; if (section === "economy") return "economy.admin"; if (section === "notifications") return "notifications.write"; if (section === "audit") return "audit.read"; return "admin.dashboard.read"; }

  private changeUserStatus(actor: AuthenticatedPrincipal, userId: string, status: "PENDING" | "ACTIVE" | "SUSPENDED" | "CLOSED", reason: string) { requirePermission(actor, "users.write"); const why = clean(reason, 3, 1000, "Причина"); return this.transactions.run(async ({ database, occurredAt }) => { const profile = await database.userProfile.findUnique({ where: { userId }, include: { playerProfile: true, partnerProfile: true } }); if (!profile) throw new ApplicationError("NOT_FOUND", "Профиль пользователя не найден"); if (profile.accountStatus === status) return { id: userId, status }; await database.userProfile.update({ where: { id: profile.id }, data: { accountStatus: status, accountStatusReason: why } }); await database.user.update({ where: { id: userId }, data: { disabledAt: ["SUSPENDED", "CLOSED"].includes(status) ? occurredAt : null } }); if (["SUSPENDED", "CLOSED"].includes(status)) await database.session.updateMany({ where: { userId, revokedAt: null }, data: { revokedAt: occurredAt } }); if (profile.playerProfile) await database.playerProfile.update({ where: { id: profile.playerProfile.id }, data: { participationStatus: status } }); if (profile.partnerProfile) await database.partnerProfile.update({ where: { id: profile.partnerProfile.id }, data: { status } }); await database.userAccountStatusHistory.create({ data: { userId, userProfileId: profile.id, actorId: actor.userId, fromStatus: profile.accountStatus, toStatus: status, reason: why, occurredAt } }); await createTransactionalEventServices(database, occurredAt).audit.record({ actor: { type: "user", id: actor.userId, sessionId: actor.sessionId }, action: "admin.user.status.changed", target: { type: "user", id: userId }, metadata: { fromStatus: profile.accountStatus, toStatus: status, reason: why } }); return { id: userId, status }; }); }

  private changeUserRole(actor: AuthenticatedPrincipal, userId: string, role: "PLAYER" | "PARTNER", reason: string) { requirePermission(actor, "users.role.write"); const why = clean(reason, 3, 1000, "Причина"); return this.transactions.run(async ({ database, occurredAt }) => { const profile = await database.userProfile.findUnique({ where: { userId }, include: { playerProfile: true, partnerProfile: true, user: { include: { _count: { select: { userTasks: true, vxRewards: true, supportConversations: true } } } } } }); if (!profile) throw new ApplicationError("NOT_FOUND", "Профиль пользователя не найден"); if (profile.productRole === role) return { id: userId, role }; if (profile.accountStatus !== "PENDING" || profile.user._count.userTasks + profile.user._count.vxRewards + profile.user._count.supportConversations > 0) throw new ApplicationError("CONFLICT", "Роль можно изменить только до начала продуктовой активности"); if (role === "PLAYER") { if (profile.partnerProfile) await database.partnerProfile.delete({ where: { id: profile.partnerProfile.id } }); await database.playerProfile.upsert({ where: { userProfileId: profile.id }, create: { userProfileId: profile.id, participationStatus: "PENDING" }, update: { participationStatus: "PENDING" } }); } else { if (profile.playerProfile) await database.playerProfile.delete({ where: { id: profile.playerProfile.id } }); await database.partnerProfile.upsert({ where: { userProfileId: profile.id }, create: { userProfileId: profile.id, status: "PENDING" }, update: { status: "PENDING" } }); } await database.userProfile.update({ where: { id: profile.id }, data: { productRole: role } }); await createTransactionalEventServices(database, occurredAt).audit.record({ actor: { type: "user", id: actor.userId, sessionId: actor.sessionId }, action: "admin.user.role.changed", target: { type: "user", id: userId }, metadata: { fromRole: profile.productRole, toRole: role, reason: why } }); return { id: userId, role }; }); }

  private approvePartner(actor: AuthenticatedPrincipal, userId: string, status: "ACTIVE" | "SUSPENDED" | "CLOSED", reason: string) { requirePermission(actor, "users.partner.approve"); const why = clean(reason, 3, 1000, "Причина"); return this.transactions.run(async ({ database, occurredAt }) => { const profile = await database.userProfile.findUnique({ where: { userId }, include: { partnerProfile: true } }); if (!profile?.partnerProfile || profile.productRole !== "PARTNER") throw new ApplicationError("NOT_FOUND", "Партнёрский профиль не найден"); const previous = profile.partnerProfile.status; await database.partnerProfile.update({ where: { id: profile.partnerProfile.id }, data: { status, statusReason: why, approvedById: actor.userId, approvedAt: status === "ACTIVE" ? occurredAt : profile.partnerProfile.approvedAt } }); await database.userProfile.update({ where: { id: profile.id }, data: { accountStatus: status, accountStatusReason: why } }); await database.partnerApprovalHistory.create({ data: { partnerProfileId: profile.partnerProfile.id, actorId: actor.userId, fromStatus: previous, toStatus: status, reason: why, occurredAt } }); await database.userAccountStatusHistory.create({ data: { userId, userProfileId: profile.id, actorId: actor.userId, fromStatus: profile.accountStatus, toStatus: status, reason: why, occurredAt } }); await createTransactionalEventServices(database, occurredAt).audit.record({ actor: { type: "user", id: actor.userId, sessionId: actor.sessionId }, action: "admin.partner.approval.decided", target: { type: "user", id: userId }, metadata: { fromStatus: previous, toStatus: status, reason: why } }); return { id: userId, status }; }); }

  private createContentRevision(actor: AuthenticatedPrincipal, input: ContentDraftInput, entityId?: string) { requirePermission(actor, "content.write"); const normalized = this.contentInput(input); return this.transactions.run(async ({ database, occurredAt }) => { const entity = entityId ? await this.requireContentEntity(database, normalized.kind, entityId) : await this.createContentEntity(database, actor.userId, normalized); const latest = await new PrismaAdminRepository(database).latestRevision(normalized.kind, entity.id); const { code: _protectedCode, ...safeSnapshot } = normalized; const revision = await database.adminContentRevision.create({ data: { entityType: normalized.kind, entityId: entity.id, version: (latest?.version ?? 0) + 1, status: "DRAFT", snapshot: asJson(safeSnapshot), reason: normalized.reason, createdById: actor.userId, createdAt: occurredAt } }); await this.createNativeDraftVersion(database, actor.userId, entity.id, normalized); await createTransactionalEventServices(database, occurredAt).audit.record({ actor: { type: "user", id: actor.userId, sessionId: actor.sessionId }, action: "admin.content.revision.created", target: { type: normalized.kind.toLowerCase(), id: entity.id }, metadata: { revisionId: revision.id, version: revision.version, reason: normalized.reason } }); return { id: entity.id, revisionId: revision.id, version: revision.version }; }); }

  private changeContentPublication(actor: AuthenticatedPrincipal, section: AdminSectionId, entityId: string, status: "PUBLISHED" | "ARCHIVED", reason: string) { requirePermission(actor, "content.publish"); const why = clean(reason, 3, 1000, "Причина"); return this.transactions.run(async ({ database, occurredAt }) => { const repository = new PrismaAdminRepository(database); const latestAny = section === "content" ? await repository.latestContentRevision(entityId) : null; const kind = latestAny?.entityType as ContentKind | undefined ?? this.sectionKind(section); await this.requireContentEntity(database, kind, entityId); const latest = latestAny ?? await repository.latestRevision(kind, entityId); if (!latest) throw new ApplicationError("CONFLICT", "Сначала создайте версию контента"); const revision = await database.adminContentRevision.create({ data: { entityType: kind, entityId, version: latest.version + 1, status, snapshot: latest.snapshot as Prisma.InputJsonValue, reason: why, createdById: actor.userId, publishedAt: status === "PUBLISHED" ? occurredAt : null, archivedAt: status === "ARCHIVED" ? occurredAt : null, createdAt: occurredAt } }); await this.applyPublication(database, actor.userId, kind, entityId, latest.snapshot, status, occurredAt); await createTransactionalEventServices(database, occurredAt).audit.record({ actor: { type: "user", id: actor.userId, sessionId: actor.sessionId }, action: status === "PUBLISHED" ? "admin.content.published" : "admin.content.archived", target: { type: kind.toLowerCase(), id: entityId }, metadata: { revisionId: revision.id, reason: why } }); return { id: entityId, status, revision: revision.version }; }); }

  private moderate(actor: AuthenticatedPrincipal, submissionVersionId: string, command: Extract<AdminCommand, { action: "MODERATION_DECISION" }>) { requirePermission(actor, "moderation.write"); const reason = clean(command.reason, 3, 1000, "Причина решения"); const reasonCode = clean(command.reasonCode, 2, 120, "Код причины"); return this.transactions.run(async ({ database, occurredAt }) => { const submission = await database.submissionVersion.findUnique({ where: { id: submissionVersionId }, include: { reviews: true, taskSubmission: { include: { userTask: true } } } }); if (!submission || submission.status !== "SUBMITTED") throw new ApplicationError("NOT_FOUND", "Отправленный результат не найден"); if (submission.reviews.length) throw new ApplicationError("CONFLICT", "Для этой версии решение уже принято"); const task = submission.taskSubmission.userTask; if (task.status !== "UNDER_REVIEW") throw new ApplicationError("CONFLICT", "Задание не находится на проверке"); await database.submissionReview.create({ data: { submissionVersionId, reviewerId: actor.userId, decision: command.decision, reasonCode, reason, comment: command.comment ? clean(command.comment, 1, 4000, "Комментарий") : null, decidedAt: occurredAt } }); const target = command.decision; await database.userTask.update({ where: { id: task.id }, data: { status: target, completedAt: target === "CONFIRMED" ? occurredAt : null } }); await database.userTaskStatusHistory.create({ data: { userTaskId: task.id, fromStatus: task.status, toStatus: target, actorId: actor.userId, reason, occurredAt } }); await createTransactionalEventServices(database, occurredAt).audit.record({ actor: { type: "user", id: actor.userId, sessionId: actor.sessionId }, action: "admin.submission.reviewed", target: { type: "submission-version", id: submissionVersionId }, metadata: { decision: command.decision, reasonCode, reason } }); return { id: submissionVersionId, decision: command.decision }; }); }

  private assignSupport(actor: AuthenticatedPrincipal, conversationId: string, operatorId: string, reason: string) { requirePermission(actor, "support.admin"); const why = clean(reason, 3, 500, "Причина"); return this.transactions.run(async ({ database, occurredAt }) => { const conversation = await database.supportConversation.findUnique({ where: { id: conversationId } }); const operator = await database.user.findUnique({ where: { id: operatorId }, include: { roles: { include: { permissions: true } } } }); if (!conversation) throw new ApplicationError("NOT_FOUND", "Обращение не найдено"); if (!operator?.roles.some((role) => role.permissions.some((permission) => permission.key === "support.write"))) throw new ApplicationError("FORBIDDEN", "У сотрудника нет права работы с поддержкой"); const target = conversation.status === "CREATED" ? "ASSIGNED" : conversation.status; await database.supportConversation.update({ where: { id: conversationId }, data: { assignedToId: operatorId, status: target } }); if (target !== conversation.status) await database.supportStatusHistory.create({ data: { conversationId, fromStatus: conversation.status, toStatus: target, actorId: actor.userId, reason: why, occurredAt } }); await createTransactionalEventServices(database, occurredAt).audit.record({ actor: { type: "user", id: actor.userId, sessionId: actor.sessionId }, action: "admin.support.assigned", target: { type: "support-conversation", id: conversationId }, metadata: { operatorId, reason: why } }); return { id: conversationId, operatorId }; }); }

  private addSupportText(actor: AuthenticatedPrincipal, conversationId: string, body: string, kind: "REPLY" | "NOTE") { requirePermission(actor, "support.admin"); const text = clean(body, 1, 5000, kind === "REPLY" ? "Ответ" : "Заметка"); return this.transactions.run(async ({ database, occurredAt }) => { const conversation = await database.supportConversation.findUnique({ where: { id: conversationId } }); if (!conversation) throw new ApplicationError("NOT_FOUND", "Обращение не найдено"); if (conversation.status === "CLOSED") throw new ApplicationError("CONFLICT", "Закрытое обращение нельзя изменить"); const bodyProtected = asJson(await this.protector.encrypt(encoder.encode(text), { classification: "confidential", purpose: kind === "REPLY" ? "support-message" : "support-internal-note", resourceType: "SupportConversation", resourceId: conversationId })); if (kind === "REPLY") { await database.supportMessage.create({ data: { conversationId, authorType: "OPERATOR", authorId: actor.userId, bodyProtected, createdAt: occurredAt } }); if (conversation.status !== "WAITING_USER") { await database.supportConversation.update({ where: { id: conversationId }, data: { status: "WAITING_USER" } }); await database.supportStatusHistory.create({ data: { conversationId, fromStatus: conversation.status, toStatus: "WAITING_USER", actorId: actor.userId, reason: "Оператор ответил пользователю", occurredAt } }); } } else await database.supportInternalNote.create({ data: { conversationId, authorId: actor.userId, bodyProtected, createdAt: occurredAt } }); await createTransactionalEventServices(database, occurredAt).audit.record({ actor: { type: "user", id: actor.userId, sessionId: actor.sessionId }, action: kind === "REPLY" ? "admin.support.replied" : "admin.support.note.added", target: { type: "support-conversation", id: conversationId }, metadata: { length: text.length } }); return { id: conversationId }; }); }

  private transitionSupport(actor: AuthenticatedPrincipal, conversationId: string, target: "ASSIGNED" | "WAITING_OPERATOR" | "WAITING_USER" | "RESOLVED" | "CLOSED", reason: string) { requirePermission(actor, "support.admin"); const why = clean(reason, 3, 500, "Причина"); return this.transactions.run(async ({ database, occurredAt }) => { const item = await database.supportConversation.findUnique({ where: { id: conversationId } }); if (!item) throw new ApplicationError("NOT_FOUND", "Обращение не найдено"); try { assertTransition(supportStateMachine, item.status, target); } catch { throw new ApplicationError("CONFLICT", "Переход статуса недоступен"); } await database.supportConversation.update({ where: { id: item.id }, data: { status: target, closedAt: target === "CLOSED" ? occurredAt : null } }); await database.supportStatusHistory.create({ data: { conversationId: item.id, fromStatus: item.status, toStatus: target, actorId: actor.userId, reason: why, occurredAt } }); await createTransactionalEventServices(database, occurredAt).audit.record({ actor: { type: "user", id: actor.userId, sessionId: actor.sessionId }, action: "admin.support.status.changed", target: { type: "support-conversation", id: conversationId }, metadata: { fromStatus: item.status, toStatus: target, reason: why } }); return { id: conversationId, status: target }; }); }

  private decideAppeal(actor: AuthenticatedPrincipal, appealId: string, target: "UPHELD" | "PARTIALLY_UPHELD" | "DENIED", reason: string) { requirePermission(actor, "appeals.write"); const why = clean(reason, 3, 1000, "Причина"); return this.transactions.run(async ({ database, occurredAt }) => { const appeal = await database.appeal.findUnique({ where: { id: appealId } }); if (!appeal) throw new ApplicationError("NOT_FOUND", "Апелляция не найдена"); if (!["SUBMITTED", "UNDER_REVIEW"].includes(appeal.status)) throw new ApplicationError("CONFLICT", "Апелляция не ожидает решения"); await database.appeal.update({ where: { id: appealId }, data: { status: target, reviewerId: actor.userId, decisionReason: why, decidedAt: occurredAt } }); await database.appealStatusHistory.create({ data: { appealId, fromStatus: appeal.status, toStatus: target, actorId: actor.userId, reason: why, occurredAt } }); await createTransactionalEventServices(database, occurredAt).audit.record({ actor: { type: "user", id: actor.userId, sessionId: actor.sessionId }, action: "admin.appeal.decided", target: { type: "appeal", id: appealId }, metadata: { decision: target, reason: why } }); return { id: appealId, status: target }; }); }

  private adjustEconomy(actor: AuthenticatedPrincipal, command: Extract<AdminCommand, { action: "ECONOMY_ADJUST" }>) { requirePermission(actor, "economy.admin"); if (!idempotencyPattern.test(command.idempotencyKey)) throw new ApplicationError("VALIDATION", "Некорректный ключ идемпотентности"); if (!Number.isInteger(command.delta) || command.delta === 0 || Math.abs(command.delta) > 100000) throw new ApplicationError("VALIDATION", "Некорректное значение корректировки"); const reason = clean(command.reason, 5, 500, "Причина"); return this.transactions.run(async ({ database, occurredAt }) => { const user = await database.user.findUnique({ where: { id: command.userId }, include: { profile: true } }); if (!user?.profile) throw new ApplicationError("NOT_FOUND", "Пользователь не найден"); const replay = await database.idempotencyRecord.findUnique({ where: { operation_key: { operation: "admin.economy.adjust", key: command.idempotencyKey } } }); if (replay) return { id: replay.resultId, replayed: true }; let resultId: string; if (command.kind === "POINTS") { const entry = await database.vXPointsLedgerEntry.create({ data: { userId: command.userId, delta: command.delta, status: "CONFIRMED", sourceType: "ADMIN_ADJUSTMENT", sourceId: actor.userId, reason, ruleVersion: "admin-manual-v1", idempotencyKey: command.idempotencyKey, occurredAt } }); resultId = entry.id; } else { const snapshot = await database.trustScoreSnapshot.findUnique({ where: { userId: command.userId } }); const before = snapshot?.score ?? 0; const after = Math.min(100, Math.max(0, before + command.delta)); const event = await database.trustScoreEvent.create({ data: { userId: command.userId, delta: after - before, scoreBefore: before, scoreAfter: after, eventType: "ADMIN_ADJUSTMENT", sourceType: "ADMIN", sourceId: actor.userId, reason, ruleVersion: "admin-manual-v1", isAppealable: true, idempotencyKey: command.idempotencyKey, occurredAt } }); await database.trustScoreSnapshot.upsert({ where: { userId: command.userId }, create: { userId: command.userId, score: after, lastEventId: event.id, calculatedAt: occurredAt }, update: { score: after, lastEventId: event.id, calculatedAt: occurredAt } }); resultId = event.id; } await database.idempotencyRecord.create({ data: { operation: "admin.economy.adjust", key: command.idempotencyKey, actorId: actor.userId, requestHash: createHash("sha256").update(JSON.stringify(command)).digest("hex"), resultType: command.kind, resultId, createdAt: occurredAt } }); await createTransactionalEventServices(database, occurredAt).audit.record({ actor: { type: "user", id: actor.userId, sessionId: actor.sessionId }, action: "admin.economy.adjusted", target: { type: command.kind.toLowerCase(), id: resultId }, metadata: { userId: command.userId, delta: command.delta, reason } }); return { id: resultId, replayed: false }; }); }

  private sendNotifications(actor: AuthenticatedPrincipal, command: Extract<AdminCommand, { action: "NOTIFY" }>) { requirePermission(actor, "notifications.write"); if (!idempotencyPattern.test(command.idempotencyKey)) throw new ApplicationError("VALIDATION", "Некорректный ключ идемпотентности"); const type = clean(command.type, 2, 120, "Категория"); const title = clean(command.title, 3, 240, "Заголовок"); const body = clean(command.body, 1, 5000, "Текст"); return this.transactions.run(async ({ database, occurredAt }) => { const replay = await database.notificationBatch.findUnique({ where: { idempotencyKey: command.idempotencyKey } }); if (replay) return replay; const users = await database.user.findMany({ where: { ...(command.userId ? { id: command.userId } : {}), profile: { accountStatus: "ACTIVE", ...(command.role ? { productRole: command.role } : {}), ...(command.market ? { market: { code: command.market } } : {}) } }, select: { id: true }, take: 500 }); if (!users.length) throw new ApplicationError("NOT_FOUND", "Получатели не найдены"); const batch = await database.notificationBatch.create({ data: { actorId: actor.userId, audience: asJson({ userId: command.userId ?? null, role: command.role ?? null, market: command.market ?? null }), type, title, body, recipientCount: users.length, idempotencyKey: command.idempotencyKey, createdAt: occurredAt } }); for (const user of users) { const notification = await database.notification.create({ data: { userId: user.id, type, channel: "IN_APP", status: "SENT", title, body, idempotencyKey: `${command.idempotencyKey}:${user.id}`, batchId: batch.id, sentAt: occurredAt, createdAt: occurredAt } }); await database.notificationStatusHistory.create({ data: { notificationId: notification.id, fromStatus: null, toStatus: "SENT", actorId: actor.userId, reason: "Административная отправка", occurredAt } }); } await createTransactionalEventServices(database, occurredAt).audit.record({ actor: { type: "user", id: actor.userId, sessionId: actor.sessionId }, action: "admin.notifications.sent", target: { type: "notification-batch", id: batch.id }, metadata: { recipientCount: users.length, role: command.role ?? null, market: command.market ?? null } }); return batch; }); }

  private contentInput(input: ContentDraftInput) {
    const now = new Date(); const week = new Date(now.getTime() + 7 * 86_400_000);
    const validFrom = input.validFrom ? new Date(input.validFrom) : now; const validUntil = input.validUntil ? new Date(input.validUntil) : week;
    if (!Number.isFinite(validFrom.getTime()) || !Number.isFinite(validUntil.getTime()) || validUntil <= validFrom) throw new ApplicationError("VALIDATION", "Укажите корректный период публикации");
    return { kind: input.kind, title: clean(input.title, 3, 240, "Название"), description: clean(input.description, 3, 5000, "Описание"), key: key(input.key, input.title), role: input.role ?? "PLAYER", market: input.market ?? "TR", nextStep: clean(input.nextStep ?? "Открыть опубликованные условия", 3, 500, "Следующий шаг"), instructionVersionId: input.instructionVersionId && uuidPattern.test(input.instructionVersionId) ? input.instructionVersionId : null, sequenceOrder: Number.isInteger(input.sequenceOrder) && Number(input.sequenceOrder) >= 0 ? Number(input.sequenceOrder) : 0, disclaimer: clean(input.disclaimer ?? "Материал носит аналитический характер и не гарантирует результат или доход.", 10, 2000, "Предупреждение"), validFrom: validFrom.toISOString(), validUntil: validUntil.toISOString(), partnerServiceId: input.partnerServiceId && uuidPattern.test(input.partnerServiceId) ? input.partnerServiceId : null, code: typeof input.code === "string" ? input.code.trim() : "", reason: clean(input.reason, 3, 1000, "Основание") };
  }
  private sectionKind(section: AdminSectionId): ContentKind { if (section === "opportunities") return "OPPORTUNITY"; if (section === "tasks") return "TASK"; if (section === "content") return "INSTRUCTION"; if (section === "rewards") return "REWARD"; throw new ApplicationError("VALIDATION", "Раздел не поддерживает версионирование контента"); }
  private requireContentEntity(database: DatabaseClient, kind: ContentKind, id: string) { if (!uuidPattern.test(id)) throw new ApplicationError("VALIDATION", "Некорректный идентификатор"); const promise = kind === "OPPORTUNITY" ? database.opportunity.findUnique({ where: { id }, select: { id: true } }) : kind === "INSTRUCTION" ? database.instruction.findUnique({ where: { id }, select: { id: true } }) : kind === "TASK" ? database.taskDefinition.findUnique({ where: { id }, select: { id: true } }) : kind === "REWARD" ? database.rewardType.findUnique({ where: { id }, select: { id: true } }) : kind === "FORECAST" ? database.forecast.findUnique({ where: { id }, select: { id: true } }) : database.promocode.findUnique({ where: { id }, select: { id: true } }); return promise.then((item) => { if (!item) throw new ApplicationError("NOT_FOUND", "Контент не найден"); return item; }); }
  private async createContentEntity(database: DatabaseClient, actorId: string, input: ReturnType<AdminApplicationService["contentInput"]>) { const market = await database.market.findUnique({ where: { code: input.market } }); if (!market) throw new ApplicationError("NOT_FOUND", "Рынок не найден"); if (input.kind === "OPPORTUNITY") return database.opportunity.create({ data: { key: input.key, type: "PERSONAL_CONDITION", title: input.title, description: input.description, status: "DRAFT", nextStep: input.nextStep, audiences: { create: { productRole: input.role, marketId: market.id } } }, select: { id: true } }); if (input.kind === "INSTRUCTION") return database.instruction.create({ data: { key: input.key, title: input.title }, select: { id: true } }); if (input.kind === "TASK") return database.taskDefinition.create({ data: { key: input.key, sequenceOrder: input.sequenceOrder, responsibleManagerId: actorId }, select: { id: true } }); if (input.kind === "REWARD") return database.rewardType.create({ data: { key: input.key, name: input.title, description: input.description, valueKind: "NON_MONETARY", status: "DRAFT" }, select: { id: true } }); if (input.kind === "FORECAST") return database.forecast.create({ data: { key: input.key, title: input.title, authorId: actorId }, select: { id: true } }); if (!input.partnerServiceId) throw new ApplicationError("VALIDATION", "Для промокода требуется партнёрский сервис"); if (input.code.length < 3 || input.code.length > 120) throw new ApplicationError("VALIDATION", "Укажите промокод длиной от 3 до 120 символов"); const id = randomUUID(); const protectedCode = await this.protector.encrypt(encoder.encode(input.code), { classification: "restricted", purpose: "promocode", resourceType: "Promocode", resourceId: id }); return database.promocode.create({ data: { id, key: input.key, partnerServiceId: input.partnerServiceId, marketId: market.id, productRole: input.role, codeProtected: asJson(protectedCode), codeFingerprint: promocodeFingerprint(input.code), instructions: input.description, validFrom: new Date(input.validFrom), validUntil: new Date(input.validUntil), status: "DRAFT" }, select: { id: true } }); }
  private async createNativeDraftVersion(database: DatabaseClient, actorId: string, entityId: string, input: ReturnType<AdminApplicationService["contentInput"]>) { const market = await database.market.findUnique({ where: { code: input.market } }); if (!market) throw new ApplicationError("NOT_FOUND", "Рынок не найден"); if (input.kind === "INSTRUCTION") { const latest = await database.instructionVersion.findFirst({ where: { instructionId: entityId }, orderBy: { version: "desc" } }); await database.instructionVersion.create({ data: { instructionId: entityId, version: (latest?.version ?? 0) + 1, status: "DRAFT", title: input.title, summary: input.description, language: "RU", contentHash: createHash("sha256").update(JSON.stringify(input)).digest("hex"), createdById: actorId, audiences: { create: { productRole: input.role, marketId: market.id } }, sections: { create: { position: 1, title: input.title, body: input.description } }, steps: { create: { position: 1, title: input.nextStep, body: input.description, isRequired: true } } } }); } if (input.kind === "TASK") { await database.taskDefinition.update({ where: { id: entityId }, data: { sequenceOrder: input.sequenceOrder } }); const latest = await database.taskVersion.findFirst({ where: { taskDefinitionId: entityId }, orderBy: { version: "desc" } }); await database.taskVersion.create({ data: { taskDefinitionId: entityId, version: (latest?.version ?? 0) + 1, status: "DRAFT", title: input.title, summary: input.description, requirements: [], limitations: [], resultRequirements: [], instructionVersionId: input.instructionVersionId, resubmissionPolicy: "Повторная отправка доступна только после решения проверяющего.", termsHash: createHash("sha256").update(JSON.stringify(input)).digest("hex"), audiences: { create: { productRole: input.role, marketId: market.id } } } }); } if (input.kind === "FORECAST") { const latest = await database.forecastVersion.findFirst({ where: { forecastId: entityId, language: "RU" }, orderBy: { version: "desc" } }); await database.forecastVersion.create({ data: { forecastId: entityId, version: (latest?.version ?? 0) + 1, language: "RU", status: "DRAFT", content: asJson({ summary: input.description, body: input.description, context: [] }), contentHash: createHash("sha256").update(JSON.stringify(input)).digest("hex"), disclaimer: input.disclaimer, validFrom: new Date(input.validFrom), validUntil: new Date(input.validUntil), accessRules: { create: { productRole: input.role, marketId: market.id, ruleVersion: `forecast-${(latest?.version ?? 0) + 1}` } } } }); } }
  private async applyPublication(database: DatabaseClient, actorId: string, kind: ContentKind, id: string, snapshot: Prisma.JsonValue, status: "PUBLISHED" | "ARCHIVED", occurredAt: Date) {
    const data = snapshot && typeof snapshot === "object" && !Array.isArray(snapshot) ? snapshot as Record<string, unknown> : {};
    if (kind === "OPPORTUNITY") await database.opportunity.update({ where: { id }, data: { status, title: String(data.title ?? ""), description: String(data.description ?? ""), nextStep: String(data.nextStep ?? ""), publishedAt: status === "PUBLISHED" ? occurredAt : undefined, archivedAt: status === "ARCHIVED" ? occurredAt : null } });
    else if (kind === "INSTRUCTION") { const version = await database.instructionVersion.findFirst({ where: { instructionId: id, status: status === "PUBLISHED" ? "DRAFT" : { in: ["DRAFT", "PUBLISHED", "HIDDEN"] } }, orderBy: { version: "desc" } }); if (!version) throw new ApplicationError("CONFLICT", "Версия инструкции не найдена"); await database.instructionVersion.update({ where: { id: version.id }, data: { status, publishedAt: status === "PUBLISHED" ? occurredAt : version.publishedAt } }); await database.instruction.update({ where: { id }, data: { title: String(data.title ?? "") } }); }
    else if (kind === "TASK") { const version = await database.taskVersion.findFirst({ where: { taskDefinitionId: id, status: status === "PUBLISHED" ? "DRAFT" : { in: ["DRAFT", "PUBLISHED", "HIDDEN"] } }, orderBy: { version: "desc" } }); if (!version) throw new ApplicationError("CONFLICT", "Версия задания не найдена"); await database.taskVersion.update({ where: { id: version.id }, data: { status, publishedAt: status === "PUBLISHED" ? occurredAt : version.publishedAt } }); }
    else if (kind === "REWARD") await database.rewardType.update({ where: { id }, data: { name: String(data.title ?? ""), description: String(data.description ?? ""), status } });
    else if (kind === "PROMOCODE") { await database.promocode.update({ where: { id }, data: { instructions: String(data.description ?? ""), validFrom: new Date(String(data.validFrom)), validUntil: new Date(String(data.validUntil)), status } }); if (status === "PUBLISHED") await this.notifyAudience(database, actorId, String(data.role), String(data.market), "promocode.published", "Доступен новый промокод", String(data.title ?? "Новый промокод VX House"), "PROMOCODE", id, occurredAt); }
    else {
      const version = await database.forecastVersion.findFirst({ where: { forecastId: id, status: status === "PUBLISHED" ? "DRAFT" : { in: ["DRAFT", "IN_REVIEW", "PUBLISHED", "SUPERSEDED", "RETRACTED"] } }, include: { accessRules: { include: { market: true } } }, orderBy: { version: "desc" } });
      if (!version) throw new ApplicationError("CONFLICT", "Версия прогноза не найдена");
      if (status === "PUBLISHED") await database.forecastVersion.updateMany({ where: { forecastId: id, status: "PUBLISHED", id: { not: version.id } }, data: { status: "SUPERSEDED" } });
      await database.forecastVersion.update({ where: { id: version.id }, data: { status: status === "PUBLISHED" ? "PUBLISHED" : "ARCHIVED", publishedAt: status === "PUBLISHED" ? occurredAt : version.publishedAt } });
      await database.forecast.update({ where: { id }, data: { title: String(data.title ?? "") } });
      if (status === "PUBLISHED") for (const rule of version.accessRules) await this.notifyAudience(database, actorId, rule.productRole, rule.market.code, "forecast.published", "Опубликован новый прогноз", String(data.title ?? "Аналитический материал VX House"), "FORECAST", id, occurredAt);
    }
  }

  private async notifyAudience(database: DatabaseClient, actorId: string, role: string, market: string, type: string, title: string, body: string, relatedType: string, relatedId: string, occurredAt: Date) {
    const users = await database.user.findMany({ where: { profile: { accountStatus: "ACTIVE", productRole: role as "PLAYER" | "PARTNER", market: { code: market as "TR" | "AZ" } } }, select: { id: true }, take: 500 });
    for (const user of users) await createProductNotification(database, { userId: user.id, type, title, body, relatedType, relatedId, idempotencyKey: `${type}:${relatedId}:${user.id}:${occurredAt.getTime()}`, actorId, occurredAt });
  }
}
