import type { Locale } from "./config";

export type StoryKind = "tasks" | "rewards" | "manager";

const en = {
  stories: {
    tasks: { eyebrow: "Your route", title: "Complete tasks step by step", description: "Every task has clear instructions, terms and a next step. A new task opens after the previous one is reviewed.", items: ["Current instructions", "Clear review status", "Result history"] },
    rewards: { eyebrow: "Your progress", title: "Unlock new benefits", description: "Confirmed actions can move your progress forward and unlock VX House benefits under the published terms.", items: ["VX Points", "Cashback and rewards", "Member levels"] },
    manager: { eyebrow: "Personal contact", title: "Your manager is always close", description: "The private conversation keeps the history and task context, so you do not need to explain the situation again.", items: ["Messages in one place", "Task context", "Conversation history"] },
  },
  space: "Personal space", controlled: "Everything is under control", firstHint: "You can immediately see what to do next.", statusHint: "The status is updated in your personal space.",
  consent: { eyebrow: "Required confirmations", title: "Review your choice and confirm the terms", description: "Only published versions of the required documents for the selected market and language are recorded.", heading: "Confirmations", current: "Current document versions", adult: "I am at least 18 years old", adultHelp: "VX House is available to adults only.", version: "Version {version}. Your consent will be linked to this published version.", missing: "Required documents have not been published for this market. Continuing is safely blocked.", summary: "Summary", scenario: "Your selected route", role: "Role", country: "Country", partnerNote: "Partner access may require separate approval.", playerNote: "Available opportunities will be determined after your profile and market are confirmed.", ready: "All required confirmations are selected.", blocked: "Confirm your age and all documents to continue.", finishing: "Finishing…", finish: "Finish setup" },
  complete: { eyebrow: "Introduction complete", thanks: "Thank you{name}.", partnerLead: "Your profile is confirmed. Partner access is awaiting a team decision.", playerLead: "Your route is ready. Start with the first available task.", summary: "Selected route", role: "Role", country: "Country", language: "Language", next: "Next step", partnerTitle: "Partner access review", playerTitle: "Secure sign-in is ready", partnerText: "You can open the partner space in a limited state. Approval is handled separately.", playerText: "For future visits, use your email and the password you created.", updates: "All changes will appear in your personal space.", tasks: "Go to tasks", restart: "Start over" },
  labels: { player: "Player", partner: "Partner", turkey: "Türkiye", azerbaijan: "Azerbaijan" },
};

const ru: typeof en = {
  stories: {
    tasks: { eyebrow: "Ваш маршрут", title: "Выполняйте задания по шагам", description: "Каждое задание содержит понятную инструкцию, условия и следующий шаг. Новое задание открывается после проверки предыдущего.", items: ["Актуальная инструкция", "Понятный статус проверки", "История результата"] },
    rewards: { eyebrow: "Ваш прогресс", title: "Открывайте новые преимущества", description: "Подтверждённые действия продвигают ваш прогресс и открывают преимущества VX House по опубликованным условиям.", items: ["VX Points", "Кешбэк и награды", "Уровни участника"] },
    manager: { eyebrow: "Личный контакт", title: "Ваш менеджер всегда рядом", description: "Внутренний диалог сохраняет историю и контекст задания. Не нужно каждый раз объяснять ситуацию заново.", items: ["Сообщения в одном месте", "Контекст заданий", "История диалога"] },
  },
  space: "Личное пространство", controlled: "Всё под контролем", firstHint: "Сразу видно, что делать дальше.", statusHint: "Статус обновляется в личном пространстве.",
  consent: { eyebrow: "Обязательные подтверждения", title: "Проверьте выбор и подтвердите условия", description: "Фиксируются только опубликованные версии обязательных документов для выбранного рынка и языка.", heading: "Подтверждения", current: "Актуальные версии документов", adult: "Мне исполнилось 18 лет", adultHelp: "VX House предназначен только для совершеннолетних пользователей.", version: "Версия {version}. Согласие будет связано именно с этой опубликованной версией.", missing: "Для выбранного рынка не опубликованы обязательные документы. Продолжение безопасно заблокировано.", summary: "Сводка", scenario: "Ваш предварительный сценарий", role: "Роль", country: "Страна", partnerNote: "Партнёрская роль может потребовать ручного подтверждения.", playerNote: "Конкретные возможности будут определены после подтверждения профиля и рынка.", ready: "Все обязательные подтверждения отмечены.", blocked: "Чтобы продолжить, подтвердите возраст и все документы.", finishing: "Завершаем…", finish: "Завершить настройку" },
  complete: { eyebrow: "Знакомство завершено", thanks: "Спасибо{name}.", partnerLead: "Профиль подтверждён. Партнёрский доступ ожидает решения команды.", playerLead: "Ваш маршрут настроен. Начните с первого доступного задания.", summary: "Выбранный сценарий", role: "Роль", country: "Страна", language: "Язык", next: "Следующий этап", partnerTitle: "Проверка партнёрского доступа", playerTitle: "Безопасный вход настроен", partnerText: "Вы можете открыть партнёрское пространство в ограниченном состоянии. Решение об одобрении принимается отдельно.", playerText: "Для следующих посещений используйте электронную почту и созданный пароль.", updates: "Все изменения появятся в личном пространстве.", tasks: "Перейти к заданиям", restart: "Начать заново" },
  labels: { player: "Игрок", partner: "Партнёр", turkey: "Турция", azerbaijan: "Азербайджан" },
};

const tr: typeof en = {
  stories: {
    tasks: { eyebrow: "Rotanız", title: "Görevleri adım adım tamamlayın", description: "Her görev açık talimatlar, koşullar ve bir sonraki adımı içerir. Yeni görev, önceki görev incelendikten sonra açılır.", items: ["Güncel talimat", "Açık inceleme durumu", "Sonuç geçmişi"] },
    rewards: { eyebrow: "İlerlemeniz", title: "Yeni avantajların kilidini açın", description: "Onaylanan işlemler ilerlemenizi artırır ve yayınlanmış koşullara göre VX House avantajlarını açar.", items: ["VX Points", "Cashback ve ödüller", "Üyelik seviyeleri"] },
    manager: { eyebrow: "Kişisel iletişim", title: "Yöneticiniz her zaman yanınızda", description: "Özel görüşme geçmişi ve görev bağlamını korur; durumu tekrar açıklamanız gerekmez.", items: ["Tüm mesajlar tek yerde", "Görev bağlamı", "Görüşme geçmişi"] },
  },
  space: "Kişisel alan", controlled: "Her şey kontrol altında", firstHint: "Bir sonraki adım hemen görünür.", statusHint: "Durum kişisel alanınızda güncellenir.",
  consent: { eyebrow: "Zorunlu onaylar", title: "Seçiminizi gözden geçirin ve koşulları onaylayın", description: "Yalnızca seçilen pazar ve dil için yayınlanan zorunlu belge sürümleri kaydedilir.", heading: "Onaylar", current: "Güncel belge sürümleri", adult: "18 yaşımı doldurdum", adultHelp: "VX House yalnızca yetişkinler içindir.", version: "Sürüm {version}. Onayınız bu yayınlanmış sürümle ilişkilendirilecektir.", missing: "Bu pazar için zorunlu belgeler yayınlanmamış. Devam etme güvenli biçimde engellendi.", summary: "Özet", scenario: "Seçtiğiniz rota", role: "Rol", country: "Ülke", partnerNote: "Partner erişimi ayrıca onay gerektirebilir.", playerNote: "Fırsatlar, profiliniz ve pazarınız onaylandıktan sonra belirlenecektir.", ready: "Tüm zorunlu onaylar seçildi.", blocked: "Devam etmek için yaşınızı ve tüm belgeleri onaylayın.", finishing: "Tamamlanıyor…", finish: "Kurulumu tamamla" },
  complete: { eyebrow: "Tanıtım tamamlandı", thanks: "Teşekkürler{name}.", partnerLead: "Profiliniz onaylandı. Partner erişimi ekip kararını bekliyor.", playerLead: "Rotanız hazır. İlk kullanılabilir görevle başlayın.", summary: "Seçilen rota", role: "Rol", country: "Ülke", language: "Dil", next: "Sonraki adım", partnerTitle: "Partner erişimi incelemesi", playerTitle: "Güvenli giriş hazır", partnerText: "Partner alanını sınırlı durumda açabilirsiniz. Onay ayrıca değerlendirilir.", playerText: "Sonraki ziyaretlerde e-posta adresinizi ve oluşturduğunuz parolayı kullanın.", updates: "Tüm değişiklikler kişisel alanınızda görünecektir.", tasks: "Görevlere git", restart: "Baştan başla" },
  labels: { player: "Oyuncu", partner: "Partner", turkey: "Türkiye", azerbaijan: "Azerbaycan" },
};

const az: typeof en = {
  stories: {
    tasks: { eyebrow: "Marşrutunuz", title: "Tapşırıqları addım-addım yerinə yetirin", description: "Hər tapşırıq aydın təlimat, şərtlər və növbəti addımı ehtiva edir. Yeni tapşırıq əvvəlki yoxlanıldıqdan sonra açılır.", items: ["Aktual təlimat", "Aydın yoxlama statusu", "Nəticə tarixçəsi"] },
    rewards: { eyebrow: "İrəliləyişiniz", title: "Yeni üstünlükləri açın", description: "Təsdiqlənmiş fəaliyyətlər irəliləyişinizi artırır və dərc olunmuş şərtlərə uyğun VX House üstünlüklərini açır.", items: ["VX Points", "Keşbek və mükafatlar", "Üzvlük səviyyələri"] },
    manager: { eyebrow: "Şəxsi əlaqə", title: "Meneceriniz həmişə yanınızdadır", description: "Şəxsi dialoq tarixçəni və tapşırıq kontekstini saxlayır; vəziyyəti yenidən izah etməyə ehtiyac qalmır.", items: ["Bütün mesajlar bir yerdə", "Tapşırıq konteksti", "Dialoq tarixçəsi"] },
  },
  space: "Şəxsi məkan", controlled: "Hər şey nəzarət altındadır", firstHint: "Növbəti addım dərhal görünür.", statusHint: "Status şəxsi məkanınızda yenilənir.",
  consent: { eyebrow: "Məcburi təsdiqlər", title: "Seçiminizi yoxlayın və şərtləri təsdiqləyin", description: "Yalnız seçilmiş bazar və dil üçün dərc edilmiş məcburi sənəd versiyaları qeydə alınır.", heading: "Təsdiqlər", current: "Aktual sənəd versiyaları", adult: "18 yaşım tamam olub", adultHelp: "VX House yalnız yetkin istifadəçilər üçündür.", version: "Versiya {version}. Razılığınız məhz bu dərc edilmiş versiya ilə əlaqələndiriləcək.", missing: "Bu bazar üçün məcburi sənədlər dərc edilməyib. Davam etmək təhlükəsiz şəkildə bloklanıb.", summary: "Xülasə", scenario: "Seçdiyiniz marşrut", role: "Rol", country: "Ölkə", partnerNote: "Tərəfdaş girişi ayrıca təsdiq tələb edə bilər.", playerNote: "İmkanlar profiliniz və bazarınız təsdiqləndikdən sonra müəyyən ediləcək.", ready: "Bütün məcburi təsdiqlər seçilib.", blocked: "Davam etmək üçün yaşınızı və bütün sənədləri təsdiqləyin.", finishing: "Tamamlanır…", finish: "Quraşdırmanı tamamla" },
  complete: { eyebrow: "Tanışlıq tamamlandı", thanks: "Təşəkkür edirik{name}.", partnerLead: "Profiliniz təsdiqləndi. Tərəfdaş girişi komandanın qərarını gözləyir.", playerLead: "Marşrutunuz hazırdır. İlk mövcud tapşırıqla başlayın.", summary: "Seçilmiş marşrut", role: "Rol", country: "Ölkə", language: "Dil", next: "Növbəti addım", partnerTitle: "Tərəfdaş girişinin yoxlanması", playerTitle: "Təhlükəsiz giriş hazırdır", partnerText: "Tərəfdaş məkanını məhdud vəziyyətdə aça bilərsiniz. Təsdiq ayrıca qiymətləndirilir.", playerText: "Növbəti girişlərdə e-poçtunuzu və yaratdığınız parolu istifadə edin.", updates: "Bütün dəyişikliklər şəxsi məkanınızda görünəcək.", tasks: "Tapşırıqlara keç", restart: "Yenidən başla" },
  labels: { player: "Oyunçu", partner: "Tərəfdaş", turkey: "Türkiyə", azerbaijan: "Azərbaycan" },
};

export const accessContent: Readonly<Record<Locale, typeof en>> = { en, ru, tr, az };
