import type { Locale } from "./config";

const en = {
  model: { eyebrow: "VX House opportunities", title: "Everything you need in one place", description: "See available offers, review the terms in advance, complete the required actions and track rewards in your account.", aria: "VX House usage scenarios", boundary: "VX House does not accept bets or hold user funds. All actions take place on partner services.", roles: [
    { label: "For players", title: "Special terms and rewards", description: "Access partner offers, complete clear tasks and receive cashback, bonuses and other rewards under the program terms.", points: ["Terms are clear in advance", "Step-by-step instructions", "Task and credit history", "Support at every stage"] },
    { label: "For partners", title: "Ready-to-use scenarios and guidance", description: "Access forecasts, materials and working scenarios, track statuses and get help inside the platform.", points: ["Forecasts and materials", "Clear working scenarios", "Status tracking", "Support and guidance"] },
  ] },
  process: { eyebrow: "How it works", title: "Four simple steps", description: "After registration, you immediately see available opportunities and participation terms.", steps: [["Create an account", "Choose a role, enter the basic details and access your account."], ["Choose an offer", "Review the terms, deadlines and potential reward before taking part."], ["Follow the instructions", "Complete the task step by step and submit your result for review."], ["Receive your reward", "Once approved, the result and credit appear in your account."]] },
  platform: { eyebrow: "Personal account", title: "Everything important at a glance", description: "Offers, tasks, rewards, support and history live in one account. You always know the current status and next step.", cta: "Get access" },
  benefits: { eyebrow: "Why VX House", title: "More opportunities. Less uncertainty.", description: "Offers, tasks, support and rewards are brought together so you can understand the rules in advance and follow every action.", items: [["Terms unavailable publicly", "Members access special partner offers and programs."], ["Transparent rewards", "Amounts, rules and credit status appear in your account."], ["Clear instructions", "Every task includes specific steps, deadlines and requirements."], ["Responsive support", "The team helps with tasks, reviews and credits."], ["Complete activity history", "Tasks, results, conversations and credits remain in your profile."], ["Reviewed partner programs", "Offers pass internal review and moderation before publication."]] },
  responsibility: { eyebrow: "Responsible participation", title: "Participate consciously", description: "VX House is for adults only. Participation is not a guaranteed way to earn money. Always review the offer terms and assess possible risks before starting.", rules: ["Do not use borrowed funds", "Set personal limits", "Contact support whenever you have questions"], note: "VX House does not accept bets or deposits and does not hold gaming balances." },
  faq: { eyebrow: "Questions and answers", title: "What to know before registration", description: "A short guide to VX House opportunities, participation terms and the personal account.", items: [["What is VX House?", "A loyalty and collaboration platform that brings together available terms, instructions, result verification and the history of interaction with partner services."], ["Does VX House accept bets or deposits?", "No. VX House is not a gaming platform, does not accept bets or deposits and does not hold gaming balances. Partner actions take place on the relevant service."], ["How do player and partner paths differ?", "Players receive a personal route to available terms. Partners work with collaboration terms, materials and interaction statuses."], ["How is a result verified?", "Before starting, you see the requirements and verification method. A submitted result receives a clear status, reason and next step."], ["What are VX Rewards and VX Points?", "VX Rewards are confirmed benefits. VX Points are internal progress points and are not money. They are not combined into one balance."], ["Where is the platform available?", "VX House starts in Türkiye and Azerbaijan. Availability of specific terms depends on country and is confirmed separately."], ["Who can use VX House?", "Adults only. Applicable rules and consents for the selected market must be accepted before participation."], ["How do I get help?", "Use the personal Messenger to contact your VX House manager. Your conversation history remains in one place."]], ctaLabel: "Platform access", ctaTitle: "See which opportunities are available to you", ctaText: "Create an account, choose your role and access VX House offers.", ctaNote: "Registration takes only a few minutes.", cta: "Get access" },
  footer: { description: "A private platform for special partner terms, tasks and rewards.", terms: "Terms of use", privacy: "Privacy policy", responsibility: "Responsible participation", support: "Support", legal: "VX House does not accept bets or deposits and does not hold gaming balances.", nav: "Additional navigation" },
};

const ru: typeof en = {
  model: { eyebrow: "Возможности VX House", title: "Всё необходимое в одном месте", description: "Вы видите доступные предложения, заранее знакомитесь с условиями, выполняете необходимые действия и отслеживаете вознаграждения в личном кабинете.", aria: "Сценарии использования VX House", boundary: "VX House не принимает ставки и не хранит пользовательские средства. Все действия выполняются на стороне партнёрских сервисов.", roles: [
    { label: "Для игрока", title: "Специальные условия и вознаграждения", description: "Получайте доступ к предложениям партнёров, выполняйте понятные задания и получайте кешбэк, бонусы и другие вознаграждения по условиям программы.", points: ["Условия известны заранее", "Пошаговые инструкции", "История заданий и начислений", "Поддержка на каждом этапе"] },
    { label: "Для партнёра", title: "Готовые сценарии и сопровождение", description: "Получайте прогнозы, материалы и рабочие сценарии, отслеживайте статусы и обращайтесь за помощью внутри платформы.", points: ["Прогнозы и материалы", "Понятные рабочие сценарии", "Контроль статусов", "Поддержка и сопровождение"] },
  ] },
  process: { eyebrow: "Как это работает", title: "Четыре простых шага", description: "После регистрации вы сразу видите доступные возможности и условия участия.", steps: [["Создайте аккаунт", "Выберите роль, укажите основные данные и получите доступ к личному кабинету."], ["Выберите предложение", "Ознакомьтесь с условиями, сроками и возможным вознаграждением до начала участия."], ["Выполните инструкции", "Следуйте пошаговому заданию и отправьте результат на проверку."], ["Получите вознаграждение", "После подтверждения результат и начисление появятся в личном кабинете."]] },
  platform: { eyebrow: "Личный кабинет", title: "Всё важное видно сразу", description: "Предложения, задания, вознаграждения, поддержка и история собраны в одном кабинете. Вы всегда знаете текущий статус и следующий шаг.", cta: "Получить доступ" },
  benefits: { eyebrow: "Почему VX House", title: "Больше условий. Меньше неопределённости.", description: "Мы собрали предложения, задания, поддержку и систему вознаграждений в одном пространстве, чтобы пользователь заранее понимал правила и видел историю каждого действия.", items: [["Условия, которых нет в открытом доступе", "Пользователи получают доступ к специальным предложениям и программам партнёров."], ["Прозрачные вознаграждения", "Размер, правила и статус начисления отображаются в личном кабинете."], ["Понятные инструкции", "Каждое задание содержит конкретные шаги, сроки и требования."], ["Быстрая поддержка", "Команда помогает разобраться с заданием, проверкой или начислением."], ["История всех действий", "Задания, результаты, обращения и начисления сохраняются в профиле."], ["Проверенные партнёрские программы", "Перед публикацией предложения проходят внутреннюю проверку и модерацию."]] },
  responsibility: { eyebrow: "Ответственное участие", title: "Участвуйте осознанно", description: "VX House предназначен только для совершеннолетних пользователей. Участие не является способом гарантированного заработка. Перед началом всегда изучайте условия предложения и оценивайте возможные риски.", rules: ["Не используйте заёмные средства", "Устанавливайте личные лимиты", "Обращайтесь в поддержку при возникновении вопросов"], note: "VX House не принимает ставки, депозиты и не хранит игровой баланс." },
  faq: { eyebrow: "Вопросы и ответы", title: "Главное перед регистрацией", description: "Коротко о возможностях VX House, условиях участия и работе личного кабинета.", items: [["Что такое VX House?", "Это платформа лояльности и сотрудничества, объединяющая условия, инструкции, подтверждение результата и историю взаимодействия с партнёрскими сервисами."], ["VX House принимает ставки или депозиты?", "Нет. VX House не является игровой платформой, не принимает ставки или депозиты и не хранит игровой баланс."], ["Чем отличаются сценарии игрока и партнёра?", "Игрок получает личный маршрут к доступным условиям. Партнёр работает с условиями сотрудничества, материалами и статусами."], ["Как подтверждается результат?", "До начала пользователь видит требования и способ подтверждения. Результат получает понятный статус, причину и следующий шаг."], ["Что означают VX Rewards и VX Points?", "VX Rewards — подтверждённые преимущества. VX Points — внутренние баллы прогресса, которые не являются деньгами."], ["Где доступна платформа?", "Стартовые рынки VX House — Турция и Азербайджан. Доступность условий зависит от страны."], ["Кому доступен VX House?", "Только совершеннолетним пользователям после принятия применимых правил и согласий."], ["Как получить помощь?", "Напишите персональному менеджеру во внутреннем Messenger. История разговора сохраняется в одном месте."]], ctaLabel: "Доступ к платформе", ctaTitle: "Посмотрите, какие возможности доступны вам", ctaText: "Создайте аккаунт, выберите роль и получите доступ к предложениям VX House.", ctaNote: "Регистрация занимает несколько минут.", cta: "Получить доступ" },
  footer: { description: "Закрытая платформа специальных условий, заданий и вознаграждений от партнёров.", terms: "Пользовательское соглашение", privacy: "Политика конфиденциальности", responsibility: "Ответственное участие", support: "Поддержка", legal: "VX House не принимает ставки, депозиты и не хранит игровой баланс.", nav: "Дополнительная навигация" },
};

const tr = JSON.parse(JSON.stringify(en)) as typeof en;
Object.assign(tr.model, { eyebrow: "VX House fırsatları", title: "İhtiyacınız olan her şey tek yerde", description: "Mevcut teklifleri görün, koşulları önceden inceleyin, gerekli adımları tamamlayın ve ödülleri hesabınızdan takip edin.", aria: "VX House kullanım senaryoları", boundary: "VX House bahis kabul etmez ve kullanıcı fonlarını tutmaz. Tüm işlemler partner servislerinde gerçekleşir." });
Object.assign(tr.process, { eyebrow: "Nasıl çalışır", title: "Dört basit adım", description: "Kayıttan sonra mevcut fırsatları ve katılım koşullarını hemen görürsünüz." });
Object.assign(tr.platform, { eyebrow: "Kişisel hesap", title: "Önemli olan her şey bir bakışta", description: "Teklifler, görevler, ödüller, destek ve geçmiş tek hesapta. Mevcut durumu ve sonraki adımı her zaman bilirsiniz.", cta: "Erişim al" });
Object.assign(tr.benefits, { eyebrow: "Neden VX House", title: "Daha fazla fırsat. Daha az belirsizlik.", description: "Kuralları önceden anlayabilmeniz ve her işlemi takip edebilmeniz için teklifleri, görevleri, desteği ve ödülleri tek yerde topladık." });
Object.assign(tr.responsibility, { eyebrow: "Sorumlu katılım", title: "Bilinçli katılın", description: "VX House yalnızca yetişkinler içindir. Katılım garantili bir kazanç yolu değildir. Başlamadan önce koşulları inceleyin ve olası riskleri değerlendirin.", rules: ["Borç para kullanmayın", "Kişisel sınırlar belirleyin", "Sorularınız için desteğe başvurun"], note: "VX House bahis veya depozito kabul etmez ve oyun bakiyesi tutmaz." });
Object.assign(tr.faq, { eyebrow: "Sorular ve yanıtlar", title: "Kayıttan önce bilmeniz gerekenler", description: "VX House fırsatları, katılım koşulları ve kişisel hesap hakkında kısa bilgiler.", ctaLabel: "Platform erişimi", ctaTitle: "Size sunulan fırsatları görün", ctaText: "Hesap oluşturun, rolünüzü seçin ve VX House tekliflerine erişin.", ctaNote: "Kayıt yalnızca birkaç dakika sürer.", cta: "Erişim al" });
Object.assign(tr.footer, { description: "Özel partner koşulları, görevler ve ödüller için kapalı platform.", terms: "Kullanım koşulları", privacy: "Gizlilik politikası", responsibility: "Sorumlu katılım", support: "Destek", legal: "VX House bahis veya depozito kabul etmez ve oyun bakiyesi tutmaz.", nav: "Ek navigasyon" });

const az = JSON.parse(JSON.stringify(en)) as typeof en;
Object.assign(az.model, { eyebrow: "VX House imkanları", title: "Ehtiyacınız olan hər şey bir yerdə", description: "Mövcud təklifləri görün, şərtlərlə əvvəlcədən tanış olun, addımları tamamlayın və mükafatları hesabınızda izləyin.", aria: "VX House istifadə ssenariləri", boundary: "VX House mərc qəbul etmir və istifadəçi vəsaitlərini saxlamır. Bütün əməliyyatlar tərəfdaş xidmətlərində aparılır." });
Object.assign(az.process, { eyebrow: "Necə işləyir", title: "Dörd sadə addım", description: "Qeydiyyatdan sonra mövcud imkanları və iştirak şərtlərini dərhal görürsünüz." });
Object.assign(az.platform, { eyebrow: "Şəxsi kabinet", title: "Vacib olan hər şey bir baxışda", description: "Təkliflər, tapşırıqlar, mükafatlar, dəstək və tarixçə bir kabinetdədir. Cari statusu və növbəti addımı həmişə bilirsiniz.", cta: "Giriş əldə et" });
Object.assign(az.benefits, { eyebrow: "Niyə VX House", title: "Daha çox imkan. Daha az qeyri-müəyyənlik.", description: "Qaydaları əvvəlcədən başa düşmək və hər əməliyyatı izləmək üçün təklifləri, tapşırıqları, dəstəyi və mükafatları bir məkanda topladıq." });
Object.assign(az.responsibility, { eyebrow: "Məsuliyyətli iştirak", title: "Şüurlu iştirak edin", description: "VX House yalnız yetkinlər üçündür. İştirak zəmanətli qazanc yolu deyil. Başlamazdan əvvəl şərtləri öyrənin və mümkün riskləri qiymətləndirin.", rules: ["Borc vəsaitlərdən istifadə etməyin", "Şəxsi limitlər təyin edin", "Suallarınız olduqda dəstəyə müraciət edin"], note: "VX House mərc və ya depozit qəbul etmir və oyun balansı saxlamır." });
Object.assign(az.faq, { eyebrow: "Suallar və cavablar", title: "Qeydiyyatdan əvvəl əsas məlumatlar", description: "VX House imkanları, iştirak şərtləri və şəxsi kabinet haqqında qısa məlumat.", ctaLabel: "Platformaya giriş", ctaTitle: "Sizin üçün hansı imkanların mövcud olduğunu görün", ctaText: "Hesab yaradın, rolunuzu seçin və VX House təkliflərinə giriş əldə edin.", ctaNote: "Qeydiyyat bir neçə dəqiqə çəkir.", cta: "Giriş əldə et" });
Object.assign(az.footer, { description: "Xüsusi tərəfdaş şərtləri, tapşırıqlar və mükafatlar üçün qapalı platforma.", terms: "İstifadə şərtləri", privacy: "Məxfilik siyasəti", responsibility: "Məsuliyyətli iştirak", support: "Dəstək", legal: "VX House mərc və ya depozit qəbul etmir və oyun balansı saxlamır.", nav: "Əlavə naviqasiya" });

export const publicContent: Readonly<Record<Locale, typeof en>> = { en, ru, tr, az };
