import type { Locale } from "./config";

type LandingRole = Readonly<{
  label: string;
  title: string;
  description: string;
  features: readonly string[];
}>;

type PublicLandingContent = Readonly<{
  model: Readonly<{ eyebrow: string; title: string; description: string; aria: string; boundary: string; roles: readonly LandingRole[] }>;
  process: Readonly<{ eyebrow: string; title: string; description: string; steps: readonly (readonly [string, string])[] }>;
  platform: Readonly<{ eyebrow: string; title: string; description: string; cta: string }>;
  benefits: Readonly<{ eyebrow: string; title: string; description: string; items: readonly (readonly [string, string])[] }>;
  responsibility: Readonly<{ eyebrow: string; title: string; description: string; rules: readonly string[]; note: string }>;
  faq: Readonly<{ eyebrow: string; title: string; description: string; items: readonly (readonly [string, string])[]; ctaLabel: string; ctaTitle: string; ctaText: string; ctaNote: string; cta: string }>;
  footer: Readonly<{ description: string; terms: string; privacy: string; responsibility: string; support: string; legal: string; nav: string }>;
  heroVisual: Readonly<{ aria: string; title: string; subtitle: string; items: readonly string[]; managerLabel: string; managerValue: string; historyLabel: string; historyValue: string }>;
  preview: Readonly<{
    aria: string;
    navigationAria: string;
    navigation: readonly string[];
    profile: string;
    demo: string;
    account: string;
    noRealData: string;
    route: readonly string[];
    primarySection: string;
    available: string;
    alwaysAvailable: string;
    actionLabel: string;
    actionTitle: string;
    actionText: string;
    inAccount: string;
    details: readonly string[];
    together: string;
    historySaved: string;
  }>;
}>;

const en: PublicLandingContent = {
  model: { eyebrow: "VX House access", title: "One private space for direct contact", description: "VX House brings your account and personal communication with the team together without complex mechanics or unnecessary sections.", aria: "VX House access scenarios", boundary: "VX House does not accept bets, deposits or hold user funds. All communication takes place inside your private account.", roles: [
    { label: "For players", title: "A personal account and manager", description: "Keep a direct line to your VX House manager and the complete conversation history in one secure space.", features: ["One permanent conversation", "Personal manager", "Complete message history", "Account settings"] },
    { label: "For partners", title: "A clear channel for cooperation", description: "Discuss access and cooperation with the VX House team in a private, continuous conversation.", features: ["Direct contact with the team", "Cooperation context", "Conversation history", "Profile settings"] },
  ] },
  process: { eyebrow: "How it works", title: "Four clear steps", description: "Create an account once and continue your communication with VX House in a private space.", steps: [["Choose your path", "Select player or partner and specify your starting market."], ["Create an account", "Enter your basic details and confirm your email."], ["Open your private space", "Your account and permanent Messenger conversation are ready after confirmation."], ["Message your manager", "Ask a question directly. The conversation and its context remain in one place."]] },
  platform: { eyebrow: "Personal account", title: "Your connection with VX House in one place", description: "Your profile, personal manager, Messenger history and account settings are always available in one private space.", cta: "Get access" },
  benefits: { eyebrow: "Why VX House", title: "Personal communication without unnecessary complexity", description: "The product is built around a direct, continuous connection between you and your VX House manager.", items: [["Personal manager", "A direct contact who knows the context of your conversation."], ["One permanent Messenger", "You do not need to create tickets or repeat the same information."], ["Conversation history", "Messages remain available in your private account."], ["Fast access to help", "Open Messenger from the home page, navigation or floating button."], ["Account control", "Your profile and interface settings stay close at hand."], ["Private space", "Communication and account details are not part of the public website."]] },
  responsibility: { eyebrow: "Responsible use", title: "Use the platform consciously", description: "VX House is intended only for adults. Review the applicable terms and make considered decisions when interacting with external partner services.", rules: ["Do not use borrowed funds", "Set personal limits", "Message your manager whenever you have questions"], note: "VX House does not accept bets or deposits and does not hold gaming balances." },
  faq: { eyebrow: "Questions and answers", title: "What to know before registration", description: "A short guide to access, personal accounts and communication with VX House.", items: [["What is VX House?", "A private digital space with a personal account and direct communication with the VX House team."], ["Does VX House accept bets or deposits?", "No. VX House is not a gaming service, does not accept bets or deposits and does not hold gaming balances."], ["How do player and partner paths differ?", "The selected path helps the team understand the context of your request and prepare the appropriate form of communication."], ["What happens after registration?", "After email confirmation, you can open your private account and message your personal manager."], ["Do I need to create a support request?", "No. Every user has one permanent Messenger conversation. Simply open it and write your message."], ["Where is the platform available?", "VX House starts in Türkiye and Azerbaijan. Availability is confirmed separately for each market."], ["Who can use VX House?", "Adults who accept the applicable rules and privacy policy for their selected market."], ["Where can I change account settings?", "Profile and interface settings are available directly in your private account."]], ctaLabel: "Private access", ctaTitle: "Open your VX House space", ctaText: "Create an account and get a direct communication channel with your personal manager.", ctaNote: "Registration takes only a few minutes.", cta: "Get access" },
  footer: { description: "A private VX House account with direct access to your personal manager.", terms: "Terms of use", privacy: "Privacy policy", responsibility: "Responsible use", support: "Manager", legal: "VX House does not accept bets or deposits and does not hold gaming balances.", nav: "Additional navigation" },
  heroVisual: { aria: "VX House personal account and Messenger preview", title: "Your VX House space", subtitle: "Your account and manager are always close", items: ["Personal account", "Personal manager", "Messenger", "Conversation history", "Account settings"], managerLabel: "Direct contact", managerValue: "Your manager is close", historyLabel: "One conversation", historyValue: "History is saved" },
  preview: { aria: "VX House personal account interface preview", navigationAria: "Example account sections", navigation: ["Home", "Manager", "Settings"], profile: "Profile", demo: "Interface preview", account: "Personal account", noRealData: "No real data", route: ["Profile", "Messenger", "Settings"], primarySection: "Main section", available: "Available in account", alwaysAvailable: "Always close", actionLabel: "Personal contact", actionTitle: "Message your manager", actionText: "Ask a question directly and continue the same conversation at any time.", inAccount: "In your account", details: ["Personal manager", "Message history", "Account settings"], together: "Everything in one place", historySaved: "Conversation history is saved" },
};

const ru: PublicLandingContent = {
  model: { eyebrow: "Доступ к VX House", title: "Единое приватное пространство для прямой связи", description: "VX House объединяет личный аккаунт и общение с командой без сложных механик и лишних разделов.", aria: "Сценарии доступа к VX House", boundary: "VX House не принимает ставки, депозиты и не хранит средства пользователей. Общение происходит внутри приватного аккаунта.", roles: [
    { label: "Для игрока", title: "Личный аккаунт и менеджер", description: "Поддерживайте прямую связь с менеджером VX House и храните всю историю переписки в одном защищённом пространстве.", features: ["Один постоянный диалог", "Персональный менеджер", "Полная история сообщений", "Настройки аккаунта"] },
    { label: "Для партнёра", title: "Понятный канал сотрудничества", description: "Обсуждайте доступ и сотрудничество с командой VX House в приватном непрерывном диалоге.", features: ["Прямая связь с командой", "Контекст сотрудничества", "История переписки", "Настройки профиля"] },
  ] },
  process: { eyebrow: "Как это работает", title: "Четыре понятных шага", description: "Один раз создайте аккаунт и продолжайте общение с VX House в приватном пространстве.", steps: [["Выберите сценарий", "Укажите роль игрока или партнёра и выберите стартовый рынок."], ["Создайте аккаунт", "Укажите основные данные и подтвердите электронную почту."], ["Откройте личное пространство", "После подтверждения вам доступны аккаунт и постоянный диалог в Messenger."], ["Напишите менеджеру", "Задайте вопрос напрямую. История и контекст разговора сохранятся в одном месте."]] },
  platform: { eyebrow: "Личный аккаунт", title: "Ваша связь с VX House в одном месте", description: "Профиль, персональный менеджер, история Messenger и настройки аккаунта всегда доступны в едином приватном пространстве.", cta: "Получить доступ" },
  benefits: { eyebrow: "Почему VX House", title: "Персональное общение без лишней сложности", description: "Продукт построен вокруг прямой и непрерывной связи между вами и персональным менеджером VX House.", items: [["Персональный менеджер", "Прямой контакт, который знает контекст вашего разговора."], ["Один постоянный Messenger", "Не нужно создавать обращения и повторно объяснять ситуацию."], ["История переписки", "Сообщения остаются доступными в личном аккаунте."], ["Быстрый доступ к помощи", "Откройте Messenger с главной, через навигацию или плавающую кнопку."], ["Управление аккаунтом", "Профиль и настройки интерфейса всегда под рукой."], ["Приватное пространство", "Переписка и данные аккаунта не отображаются на публичном сайте."]] },
  responsibility: { eyebrow: "Ответственное использование", title: "Используйте платформу осознанно", description: "VX House предназначен только для совершеннолетних. Изучайте применимые условия и принимайте взвешенные решения при взаимодействии со сторонними партнёрскими сервисами.", rules: ["Не используйте заёмные средства", "Устанавливайте личные лимиты", "Пишите менеджеру, если у вас появились вопросы"], note: "VX House не принимает ставки, депозиты и не хранит игровой баланс." },
  faq: { eyebrow: "Вопросы и ответы", title: "Главное перед регистрацией", description: "Коротко о доступе, личном аккаунте и общении с VX House.", items: [["Что такое VX House?", "Приватное цифровое пространство с личным аккаунтом и прямой связью с командой VX House."], ["VX House принимает ставки или депозиты?", "Нет. VX House не является игровым сервисом, не принимает ставки или депозиты и не хранит игровой баланс."], ["Чем отличаются сценарии игрока и партнёра?", "Выбранный сценарий помогает команде понять контекст запроса и подготовить подходящий формат общения."], ["Что происходит после регистрации?", "После подтверждения электронной почты вы сможете открыть личный аккаунт и написать персональному менеджеру."], ["Нужно ли создавать обращение в поддержку?", "Нет. У каждого пользователя есть один постоянный диалог в Messenger. Просто откройте его и напишите сообщение."], ["Где доступна платформа?", "Стартовые рынки VX House — Турция и Азербайджан. Доступность подтверждается отдельно для каждого рынка."], ["Кому доступен VX House?", "Совершеннолетним пользователям, принявшим применимые правила и политику конфиденциальности выбранного рынка."], ["Где изменить настройки аккаунта?", "Профиль и настройки интерфейса доступны прямо в вашем личном аккаунте."]], ctaLabel: "Приватный доступ", ctaTitle: "Откройте своё пространство VX House", ctaText: "Создайте аккаунт и получите прямой канал связи с персональным менеджером.", ctaNote: "Регистрация занимает несколько минут.", cta: "Получить доступ" },
  footer: { description: "Приватный аккаунт VX House с прямым доступом к персональному менеджеру.", terms: "Пользовательское соглашение", privacy: "Политика конфиденциальности", responsibility: "Ответственное использование", support: "Менеджер", legal: "VX House не принимает ставки, депозиты и не хранит игровой баланс.", nav: "Дополнительная навигация" },
  heroVisual: { aria: "Предпросмотр личного аккаунта и Messenger VX House", title: "Ваше пространство VX House", subtitle: "Аккаунт и менеджер всегда рядом", items: ["Личный аккаунт", "Персональный менеджер", "Messenger", "История переписки", "Настройки аккаунта"], managerLabel: "Прямая связь", managerValue: "Менеджер рядом", historyLabel: "Один диалог", historyValue: "История сохраняется" },
  preview: { aria: "Демонстрация интерфейса личного аккаунта VX House", navigationAria: "Пример разделов аккаунта", navigation: ["Главная", "Менеджер", "Настройки"], profile: "Профиль", demo: "Демонстрация интерфейса", account: "Личный аккаунт", noRealData: "Без реальных данных", route: ["Профиль", "Messenger", "Настройки"], primarySection: "Основной раздел", available: "Доступно в аккаунте", alwaysAvailable: "Всегда рядом", actionLabel: "Личная связь", actionTitle: "Напишите своему менеджеру", actionText: "Задайте вопрос напрямую и продолжите тот же разговор в любое время.", inAccount: "В аккаунте", details: ["Персональный менеджер", "История сообщений", "Настройки аккаунта"], together: "Всё в одном месте", historySaved: "История переписки сохраняется" },
};

const tr: PublicLandingContent = {
  model: { eyebrow: "VX House erişimi", title: "Doğrudan iletişim için tek bir özel alan", description: "VX House, karmaşık mekanikler ve gereksiz bölümler olmadan kişisel hesabınızı ve ekiple iletişiminizi bir araya getirir.", aria: "VX House erişim senaryoları", boundary: "VX House bahis veya para yatırma işlemi kabul etmez ve kullanıcı fonlarını tutmaz. Tüm iletişim özel hesabınızda gerçekleşir.", roles: [
    { label: "Oyuncular için", title: "Kişisel hesap ve yönetici", description: "VX House yöneticinizle doğrudan bağlantınızı ve tüm görüşme geçmişinizi tek bir güvenli alanda tutun.", features: ["Tek kalıcı görüşme", "Kişisel yönetici", "Eksiksiz mesaj geçmişi", "Hesap ayarları"] },
    { label: "Partnerler için", title: "İş birliği için açık bir kanal", description: "VX House ekibiyle erişim ve iş birliğini özel ve kesintisiz bir görüşmede konuşun.", features: ["Ekiple doğrudan iletişim", "İş birliği bağlamı", "Görüşme geçmişi", "Profil ayarları"] },
  ] },
  process: { eyebrow: "Nasıl çalışır", title: "Dört açık adım", description: "Hesabınızı bir kez oluşturun ve VX House ile iletişiminizi özel alanınızda sürdürün.", steps: [["Yolunuzu seçin", "Oyuncu veya partner rolünü ve başlangıç pazarınızı seçin."], ["Hesabınızı oluşturun", "Temel bilgilerinizi girin ve e-posta adresinizi doğrulayın."], ["Özel alanınızı açın", "Doğrulamanın ardından hesabınız ve kalıcı Messenger görüşmeniz hazır olur."], ["Yöneticinize yazın", "Sorunuzu doğrudan sorun. Görüşmenin geçmişi ve bağlamı tek yerde kalır."]] },
  platform: { eyebrow: "Kişisel hesap", title: "VX House bağlantınız tek yerde", description: "Profiliniz, kişisel yöneticiniz, Messenger geçmişiniz ve hesap ayarlarınız tek bir özel alanda her zaman erişilebilir.", cta: "Erişim al" },
  benefits: { eyebrow: "Neden VX House", title: "Gereksiz karmaşa olmadan kişisel iletişim", description: "Ürün, sizinle kişisel VX House yöneticiniz arasındaki doğrudan ve kesintisiz iletişim etrafında tasarlanmıştır.", items: [["Kişisel yönetici", "Görüşmenizin bağlamını bilen doğrudan iletişim kişisi."], ["Tek kalıcı Messenger", "Talep oluşturmanız veya aynı bilgileri tekrar vermeniz gerekmez."], ["Görüşme geçmişi", "Mesajlar kişisel hesabınızda erişilebilir kalır."], ["Yardıma hızlı erişim", "Messenger'ı ana sayfadan, menüden veya yüzen düğmeden açın."], ["Hesap kontrolü", "Profiliniz ve arayüz ayarlarınız her zaman elinizin altında."], ["Özel alan", "İletişiminiz ve hesap bilgileriniz herkese açık sitede gösterilmez."]] },
  responsibility: { eyebrow: "Sorumlu kullanım", title: "Platformu bilinçli kullanın", description: "VX House yalnızca yetişkinler içindir. Harici partner servisleriyle etkileşim kurarken geçerli koşulları inceleyin ve bilinçli kararlar alın.", rules: ["Borç para kullanmayın", "Kişisel sınırlar belirleyin", "Sorularınız olduğunda yöneticinize yazın"], note: "VX House bahis veya para yatırma işlemi kabul etmez ve oyun bakiyesi tutmaz." },
  faq: { eyebrow: "Sorular ve yanıtlar", title: "Kayıttan önce bilmeniz gerekenler", description: "Erişim, kişisel hesap ve VX House iletişimi hakkında kısa bilgiler.", items: [["VX House nedir?", "Kişisel hesabınızın ve VX House ekibiyle doğrudan iletişiminizin bulunduğu özel bir dijital alandır."], ["VX House bahis veya para yatırma işlemi kabul eder mi?", "Hayır. VX House bir oyun servisi değildir; bahis veya para yatırma işlemi kabul etmez ve oyun bakiyesi tutmaz."], ["Oyuncu ve partner yolları nasıl farklıdır?", "Seçtiğiniz yol, ekibin talebinizin bağlamını anlamasına ve uygun iletişim biçimini hazırlamasına yardımcı olur."], ["Kayıttan sonra ne olur?", "E-posta doğrulamasından sonra özel hesabınızı açabilir ve kişisel yöneticinize yazabilirsiniz."], ["Destek talebi oluşturmam gerekir mi?", "Hayır. Her kullanıcının tek bir kalıcı Messenger görüşmesi vardır. Açıp mesajınızı yazmanız yeterlidir."], ["Platform nerede kullanılabilir?", "VX House Türkiye ve Azerbaycan'da başlar. Kullanılabilirlik her pazar için ayrıca doğrulanır."], ["VX House'u kimler kullanabilir?", "Seçilen pazarın geçerli kurallarını ve gizlilik politikasını kabul eden yetişkinler."], ["Hesap ayarlarını nerede değiştirebilirim?", "Profil ve arayüz ayarları doğrudan özel hesabınızda bulunur."]], ctaLabel: "Özel erişim", ctaTitle: "VX House alanınızı açın", ctaText: "Hesabınızı oluşturun ve kişisel yöneticinizle doğrudan iletişim kanalına erişin.", ctaNote: "Kayıt yalnızca birkaç dakika sürer.", cta: "Erişim al" },
  footer: { description: "Kişisel yöneticinize doğrudan erişim sunan özel VX House hesabı.", terms: "Kullanım koşulları", privacy: "Gizlilik politikası", responsibility: "Sorumlu kullanım", support: "Yönetici", legal: "VX House bahis veya para yatırma işlemi kabul etmez ve oyun bakiyesi tutmaz.", nav: "Ek navigasyon" },
  heroVisual: { aria: "VX House kişisel hesap ve Messenger önizlemesi", title: "VX House alanınız", subtitle: "Hesabınız ve yöneticiniz her zaman yanınızda", items: ["Kişisel hesap", "Kişisel yönetici", "Messenger", "Görüşme geçmişi", "Hesap ayarları"], managerLabel: "Doğrudan iletişim", managerValue: "Yöneticiniz yanınızda", historyLabel: "Tek görüşme", historyValue: "Geçmiş korunur" },
  preview: { aria: "VX House kişisel hesap arayüzü önizlemesi", navigationAria: "Örnek hesap bölümleri", navigation: ["Ana sayfa", "Yönetici", "Ayarlar"], profile: "Profil", demo: "Arayüz önizlemesi", account: "Kişisel hesap", noRealData: "Gerçek veri içermez", route: ["Profil", "Messenger", "Ayarlar"], primarySection: "Ana bölüm", available: "Hesapta mevcut", alwaysAvailable: "Her zaman yakınınızda", actionLabel: "Kişisel iletişim", actionTitle: "Yöneticinize yazın", actionText: "Sorunuzu doğrudan sorun ve aynı görüşmeye istediğiniz zaman devam edin.", inAccount: "Hesabınızda", details: ["Kişisel yönetici", "Mesaj geçmişi", "Hesap ayarları"], together: "Her şey tek yerde", historySaved: "Görüşme geçmişi korunur" },
};

const az: PublicLandingContent = {
  model: { eyebrow: "VX House girişi", title: "Birbaşa əlaqə üçün vahid şəxsi məkan", description: "VX House mürəkkəb mexanikalar və lazımsız bölmələr olmadan şəxsi hesabınızı və komanda ilə əlaqənizi birləşdirir.", aria: "VX House giriş ssenariləri", boundary: "VX House mərc və ya depozit qəbul etmir və istifadəçi vəsaitlərini saxlamır. Bütün ünsiyyət şəxsi hesabınızda aparılır.", roles: [
    { label: "Oyunçular üçün", title: "Şəxsi hesab və menecer", description: "VX House menecerinizlə birbaşa əlaqəni və bütün yazışma tarixçəsini vahid təhlükəsiz məkanda saxlayın.", features: ["Bir daimi dialoq", "Şəxsi menecer", "Tam mesaj tarixçəsi", "Hesab tənzimləmələri"] },
    { label: "Tərəfdaşlar üçün", title: "Əməkdaşlıq üçün aydın kanal", description: "VX House komandası ilə giriş və əməkdaşlığı şəxsi və davamlı dialoqda müzakirə edin.", features: ["Komanda ilə birbaşa əlaqə", "Əməkdaşlıq konteksti", "Yazışma tarixçəsi", "Profil tənzimləmələri"] },
  ] },
  process: { eyebrow: "Necə işləyir", title: "Dörd aydın addım", description: "Hesabınızı bir dəfə yaradın və VX House ilə ünsiyyəti şəxsi məkanınızda davam etdirin.", steps: [["Ssenarinizi seçin", "Oyunçu və ya tərəfdaş rolunu və başlanğıc bazarınızı seçin."], ["Hesab yaradın", "Əsas məlumatlarınızı daxil edin və e-poçtunuzu təsdiqləyin."], ["Şəxsi məkanınızı açın", "Təsdiqdən sonra hesabınız və daimi Messenger dialoqunuz hazır olur."], ["Menecerinizə yazın", "Sualınızı birbaşa verin. Söhbətin tarixçəsi və konteksti bir yerdə qalır."]] },
  platform: { eyebrow: "Şəxsi hesab", title: "VX House ilə əlaqəniz bir yerdə", description: "Profiliniz, şəxsi meneceriniz, Messenger tarixçəniz və hesab tənzimləmələriniz vahid şəxsi məkanda həmişə əlçatandır.", cta: "Giriş əldə et" },
  benefits: { eyebrow: "Niyə VX House", title: "Lazımsız mürəkkəblik olmadan şəxsi ünsiyyət", description: "Məhsul sizinlə şəxsi VX House meneceriniz arasındakı birbaşa və davamlı əlaqə üzərində qurulub.", items: [["Şəxsi menecer", "Söhbətinizin kontekstini bilən birbaşa əlaqə şəxsi."], ["Bir daimi Messenger", "Müraciət yaratmağa və eyni məlumatı təkrar izah etməyə ehtiyac yoxdur."], ["Yazışma tarixçəsi", "Mesajlar şəxsi hesabınızda əlçatan qalır."], ["Köməyə sürətli giriş", "Messenger-i ana səhifədən, naviqasiyadan və ya üzən düymədən açın."], ["Hesaba nəzarət", "Profil və interfeys tənzimləmələriniz həmişə yaxındadır."], ["Şəxsi məkan", "Yazışmanız və hesab məlumatlarınız ictimai saytda göstərilmir."]] },
  responsibility: { eyebrow: "Məsuliyyətli istifadə", title: "Platformadan şüurlu istifadə edin", description: "VX House yalnız yetkinlər üçündür. Xarici tərəfdaş xidmətləri ilə əlaqə zamanı tətbiq olunan şərtləri nəzərdən keçirin və düşünülmüş qərarlar verin.", rules: ["Borc vəsaitlərdən istifadə etməyin", "Şəxsi limitlər təyin edin", "Suallarınız olduqda menecerinizə yazın"], note: "VX House mərc və ya depozit qəbul etmir və oyun balansı saxlamır." },
  faq: { eyebrow: "Suallar və cavablar", title: "Qeydiyyatdan əvvəl əsas məlumatlar", description: "Giriş, şəxsi hesab və VX House ilə ünsiyyət haqqında qısa məlumat.", items: [["VX House nədir?", "Şəxsi hesab və VX House komandası ilə birbaşa əlaqəni birləşdirən qapalı rəqəmsal məkandır."], ["VX House mərc və ya depozit qəbul edir?", "Xeyr. VX House oyun xidməti deyil, mərc və ya depozit qəbul etmir və oyun balansı saxlamır."], ["Oyunçu və tərəfdaş ssenariləri necə fərqlənir?", "Seçilən ssenari komandaya sorğunuzun kontekstini anlamağa və uyğun ünsiyyət formasını hazırlamağa kömək edir."], ["Qeydiyyatdan sonra nə baş verir?", "E-poçtu təsdiqlədikdən sonra şəxsi hesabınızı aça və menecerinizə yaza bilərsiniz."], ["Dəstək müraciəti yaratmalıyam?", "Xeyr. Hər istifadəçinin bir daimi Messenger dialoqu var. Onu açıb mesajınızı yazmaq kifayətdir."], ["Platforma harada əlçatandır?", "VX House Türkiyə və Azərbaycanda fəaliyyətə başlayır. Əlçatanlıq hər bazar üçün ayrıca təsdiqlənir."], ["VX House kimlər üçün əlçatandır?", "Seçilmiş bazarın tətbiq olunan qaydalarını və məxfilik siyasətini qəbul edən yetkin istifadəçilər üçün."], ["Hesab tənzimləmələrini harada dəyişə bilərəm?", "Profil və interfeys tənzimləmələri birbaşa şəxsi hesabınızda mövcuddur."]], ctaLabel: "Şəxsi giriş", ctaTitle: "VX House məkanınızı açın", ctaText: "Hesab yaradın və şəxsi menecerinizlə birbaşa əlaqə kanalı əldə edin.", ctaNote: "Qeydiyyat bir neçə dəqiqə çəkir.", cta: "Giriş əldə et" },
  footer: { description: "Şəxsi menecerinizlə birbaşa əlaqə yaradan qapalı VX House hesabı.", terms: "İstifadə şərtləri", privacy: "Məxfilik siyasəti", responsibility: "Məsuliyyətli istifadə", support: "Menecer", legal: "VX House mərc və ya depozit qəbul etmir və oyun balansı saxlamır.", nav: "Əlavə naviqasiya" },
  heroVisual: { aria: "VX House şəxsi hesab və Messenger önizləməsi", title: "VX House məkanınız", subtitle: "Hesabınız və meneceriniz həmişə yanınızdadır", items: ["Şəxsi hesab", "Şəxsi menecer", "Messenger", "Yazışma tarixçəsi", "Hesab tənzimləmələri"], managerLabel: "Birbaşa əlaqə", managerValue: "Meneceriniz yanınızdadır", historyLabel: "Bir dialoq", historyValue: "Tarixçə saxlanılır" },
  preview: { aria: "VX House şəxsi hesab interfeysinin önizləməsi", navigationAria: "Hesab bölmələrinin nümunəsi", navigation: ["Ana səhifə", "Menecer", "Tənzimləmələr"], profile: "Profil", demo: "İnterfeys önizləməsi", account: "Şəxsi hesab", noRealData: "Real məlumat yoxdur", route: ["Profil", "Messenger", "Tənzimləmələr"], primarySection: "Əsas bölmə", available: "Hesabda əlçatandır", alwaysAvailable: "Həmişə yanınızda", actionLabel: "Şəxsi əlaqə", actionTitle: "Menecerinizə yazın", actionText: "Sualınızı birbaşa verin və eyni söhbəti istənilən vaxt davam etdirin.", inAccount: "Hesabda", details: ["Şəxsi menecer", "Mesaj tarixçəsi", "Hesab tənzimləmələri"], together: "Hər şey bir yerdə", historySaved: "Yazışma tarixçəsi saxlanılır" },
};

export const publicContent: Readonly<Record<Locale, PublicLandingContent>> = { en, ru, tr, az };
