import type { Locale } from "./config";

type PartnerCopy = Readonly<{
  home: Readonly<Record<string, string>>;
  profile: Readonly<Record<string, string>>;
  materials: Readonly<Record<string, string>>;
  forecasts: Readonly<Record<string, string>>;
  history: Readonly<Record<string, string>>;
  promocode: Readonly<Record<string, string>>;
}>;

type AdminCopy = Readonly<{
  overview: Readonly<Record<string, string>>;
  section: Readonly<Record<string, string>>;
  detail: Readonly<Record<string, string>>;
  editor: Readonly<Record<string, string>>;
}>;

export type WorkspaceContent = Readonly<{ partner: PartnerCopy; admin: AdminCopy }>;

const en: WorkspaceContent = {
  partner: {
    home: { area: "Partner workspace", title: "Partner workspace", description: "Your partner space uses verified server data for your role and market.", approved: "Access approved", pending: "Awaiting approval", recommended: "Recommended next step", openOpportunities: "Open work opportunities", checkProfile: "Review partner profile", noOpportunities: "There are no new applicable opportunities yet; available sections are synchronized with the server.", approvalRequired: "Work opportunities will open after partner access is approved.", openNext: "Open next step", profileState: "Partner profile status", profile: "Partner profile", active: "Active", awaitingDecision: "Awaiting decision", opportunities: "Available opportunities", unread: "Unread events", serverCalculation: "Server calculation", currentRank: "Current rank", assigned: "Assigned", undefined: "Not defined", noData: "No data", rankHelp: "Rank is determined by published criteria for the role and market.", current: "Current", confirmedBalance: "Confirmed balance", serverData: "Server data", pointsHelp: "VX Points are not money; the balance is calculated from the ledger.", cooperation: "Cooperation", accessActive: "Partner access is active", decisionPending: "Decision pending", accessHelp: "The status comes from the server partner profile and controls access to work materials.", forecasts: "Forecasts", promocodes: "Promo codes", managerMessages: "Manager messages", statistics: "Summary", activity: "Current activity", days: "Days with VX House", activeTasks: "Active tasks", completedTasks: "Completed tasks", workSections: "Work sections", partnerSpace: "Partner space" },
    profile: { area: "Partner workspace", title: "Profile", description: "Verified VX House partner profile data.", pending: "Awaiting approval", approved: "Approved", personal: "Personal details", fallback: "VX House partner", email: "Email", market: "Market", language: "Language", created: "Profile created", state: "Access status", manual: "Manual approval required", accessApproved: "Partner access approved", pendingHelp: "Your profile and contact are verified. Partner functions remain limited until the VX House team makes a decision.", approvedHelp: "Permissions are determined by the server partner profile." },
    materials: { eyebrow: "Work content", title: "Materials", description: "Promo codes and applicable partner terms verified by role, market and validity period.", count: "{count} materials", none: "No materials available", empty: "No materials have been assigned yet", emptyHelp: "The system checked the role, market, partner access status and publication dates.", back: "Back to overview" },
    forecasts: { eyebrow: "Analytical materials", title: "Forecasts", description: "Published materials with author, validity period, version history and required disclaimer.", count: "{count} available", back: "Back to overview", none: "No publications available", empty: "No current forecasts", emptyHelp: "The system checks the verified role, market, personal rules and publication period.", published: "Published", author: "Author", version: "Version", validUntil: "Valid until" },
    history: { eyebrow: "Transparent timeline", title: "Cooperation history", description: "Verified changes to the partner profile, materials and communication.", count: "{count} events", back: "Back to overview" },
    promocode: { activatedMessage: "The promo code was activated and added to history.", activationError: "The promo code could not be activated.", activated: "Activated", expired: "Expired", available: "Available", validUntil: "Valid until", role: "Role", partner: "Partner", player: "Player", copy: "Copy promo code", activating: "Activating…", activate: "Activate" },
  },
  admin: {
    overview: { eyebrow: "Administration", title: "VX House workspace", description: "Members and personal conversations in one secure interface.", serverData: "Server data", users: "Users", registrations: "New registrations", calculated: "Calculated by the server when the page opens.", analytics: "First-party analytics · 30 days", funnel: "Access funnel", funnelHelp: "Test and smoke accounts are excluded. Percentages are calculated by the server.", internalEvents: "Internal events", visitors: "Unique visitors", accessClicks: "Clicked Get access", registrationStarted: "Started registration", emailConfirmed: "Confirmed email", dashboardOpened: "Opened Dashboard", firstView: "First verified view", conversion: "Step conversion: {value}%", workspace: "Workspace", areas: "Main administration areas", areasHelp: "Only sections required for the current MVP remain in navigation.", rbac: "RBAC enabled", open: "Open", openSection: "Open section", members: "Members", membersHelp: "Player and partner profiles and statuses.", membersPurpose: "Open member list", messengerHelp: "Permanent personal conversations with members.", messengerPurpose: "Open conversation", local: "Local test environment", demo: "Ready demo accounts", demoHelp: "Accounts are created automatically when the development server starts.", localOnly: "Local only", administrator: "Administrator", playerOne: "Player 1", playerTwo: "Player 2", password: "Password", boundary: "Security boundary", safety: "Administrative actions are controlled by the server", safetyHelp: "Access to members, Messenger and tags is checked by server permissions and recorded in the audit log." },
    section: { eyebrow: "Administration", create: "Create", workspace: "Workspace", serverData: "Server data · {count}", searchFilters: "Section search and filters", search: "Search", roleFilter: "Filter by role", allRoles: "All roles", player: "Player", partner: "Partner", marketFilter: "Filter by market", allMarkets: "All markets", turkey: "Türkiye", azerbaijan: "Azerbaijan", apply: "Apply", savedViews: "Saved views", bulkHelp: "Bulk changes are available only through protected server commands.", selectRecords: "Select records", status: "Status", nextStep: "Next step", openRecord: "Open record", emptyLabel: "Empty state", empty: "No records yet", emptyHelp: "No server records match the selected filters.", pagination: "Section pagination", back: "Back", records: "{count} records on this page", next: "Next", missing: "Section not found", missingHelp: "This administration section does not exist." },
    detail: { edit: "Open editing", serverData: "Server data", rights: "Permissions and changes", control: "Server control", controlHelp: "Every command rechecks RBAC and records its reason in the immutable audit log.", history: "Change history", historyTitle: "History is preserved", historyHelp: "Status changes, publications and decisions append a new record without overwriting the past.", operation: "Operational command", operationTitle: "Perform an allowed action", operationHelp: "A reason is required and the result is recorded by the server.", backSection: "Back to {section}", noData: "No data", missing: "Entity not found", missingHelp: "The record does not exist or is unavailable with the current permissions.", backList: "Back to list" },
    editor: { noData: "No data", unavailable: "Editing unavailable", sectionMissing: "Section not found.", mode: "Editing mode", create: "Create: {section}", description: "The change creates a new server version and records the author, reason and time.", audit: "RBAC and audit", draft: "New draft", version: "New version", immutable: "The published version is not overwritten.", back: "Back" },
  },
};

const ru: WorkspaceContent = {
  partner: {
    home: { area: "Кабинет партнёра", title: "Рабочее пространство партнёра", description: "Ваше партнёрское пространство использует подтверждённые серверные данные роли и рынка.", approved: "Доступ одобрен", pending: "Ожидает одобрения", recommended: "Рекомендуемый следующий шаг", openOpportunities: "Открыть рабочие возможности", checkProfile: "Проверить партнёрский профиль", noOpportunities: "Применимых новых возможностей пока нет; доступные разделы синхронизированы с сервером.", approvalRequired: "Рабочие возможности откроются после решения по партнёрскому доступу.", openNext: "Открыть следующий шаг", profileState: "Состояние партнёрского профиля", profile: "Партнёрский профиль", active: "Активен", awaitingDecision: "Ожидает решения", opportunities: "Доступные возможности", unread: "Непрочитанные события", serverCalculation: "Серверный расчёт", currentRank: "Текущий ранг", assigned: "Назначен", undefined: "Не определён", noData: "Нет данных", rankHelp: "Ранг определяется опубликованными критериями роли и рынка.", current: "Актуально", confirmedBalance: "Подтверждённый баланс", serverData: "Серверные данные", pointsHelp: "VX Points не являются деньгами; баланс рассчитан по ledger.", cooperation: "Сотрудничество", accessActive: "Партнёрский доступ активен", decisionPending: "Ожидается решение", accessHelp: "Статус получен из серверного партнёрского профиля и определяет доступ к рабочим материалам.", forecasts: "Прогнозы", promocodes: "Промокоды", managerMessages: "Сообщения менеджера", statistics: "Краткая статистика", activity: "Текущая активность", days: "Дней с VX House", activeTasks: "Активные задачи", completedTasks: "Завершённые задачи", workSections: "Рабочие разделы", partnerSpace: "Партнёрское пространство" },
    profile: { area: "Кабинет партнёра", title: "Профиль", description: "Подтверждённые данные партнёрского профиля VX House.", pending: "Ожидает одобрения", approved: "Одобрен", personal: "Личные данные", fallback: "Партнёр VX House", email: "Электронная почта", market: "Рынок", language: "Язык", created: "Профиль создан", state: "Состояние доступа", manual: "Требуется ручное одобрение", accessApproved: "Партнёрский доступ одобрен", pendingHelp: "Профиль и контакт подтверждены. Партнёрские функции остаются ограниченными до решения команды VX House.", approvedHelp: "Права определяются серверным партнёрским профилем." },
    materials: { eyebrow: "Рабочий контент", title: "Материалы", description: "Промокоды и применимые условия партнёра с серверной проверкой роли, рынка и срока.", count: "Материалов: {count}", none: "Нет доступных материалов", empty: "Материалы пока не назначены", emptyHelp: "Система проверила роль, рынок, статус партнёрского доступа и опубликованные сроки.", back: "Вернуться к обзору" },
    forecasts: { eyebrow: "Аналитические материалы", title: "Прогнозы", description: "Опубликованные материалы с автором, сроком актуальности, историей версии и обязательным предупреждением.", count: "Доступно: {count}", back: "Вернуться к обзору", none: "Нет доступных публикаций", empty: "Актуальных прогнозов пока нет", emptyHelp: "Система учитывает подтверждённую роль, рынок, персональные правила и период публикации.", published: "Опубликован", author: "Автор", version: "Версия", validUntil: "Актуален до" },
    history: { eyebrow: "Прозрачная хронология", title: "История сотрудничества", description: "Проверяемые изменения партнёрского профиля, материалов и коммуникации.", count: "Событий: {count}", back: "Вернуться к обзору" },
    promocode: { activatedMessage: "Промокод активирован и добавлен в историю.", activationError: "Не удалось активировать промокод.", activated: "Активирован", expired: "Истёк", available: "Доступен", validUntil: "Действует до", role: "Роль", partner: "Партнёр", player: "Игрок", copy: "Скопировать промокод", activating: "Активируем…", activate: "Активировать" },
  },
  admin: {
    overview: { eyebrow: "Управляющая часть", title: "Рабочее пространство VX House", description: "Участники и персональные диалоги в одном защищённом интерфейсе.", serverData: "Серверные данные", users: "Пользователи", registrations: "Новые регистрации", calculated: "Рассчитано сервером на момент открытия страницы.", analytics: "First-party аналитика · 30 дней", funnel: "Воронка получения доступа", funnelHelp: "Тестовые и smoke-аккаунты исключены. Проценты рассчитываются сервером.", internalEvents: "Внутренние события", visitors: "Уникальные посетители", accessClicks: "Нажали «Получить доступ»", registrationStarted: "Начали регистрацию", emailConfirmed: "Подтвердили email", dashboardOpened: "Открыли Dashboard", firstView: "Первый подтверждённый просмотр", conversion: "Конверсия этапа: {value}%", workspace: "Рабочее пространство", areas: "Основные области администратора", areasHelp: "В навигации оставлены только разделы, необходимые для текущего MVP.", rbac: "RBAC включён", open: "Открыть", openSection: "Открыть раздел", members: "Участники", membersHelp: "Профили и состояние игроков и партнёров.", membersPurpose: "Открыть список участников", messengerHelp: "Постоянные личные диалоги с участниками.", messengerPurpose: "Открыть переписку", local: "Локальная тестовая среда", demo: "Готовые демо-аккаунты", demoHelp: "Аккаунты создаются автоматически при запуске development-сервера.", localOnly: "Только локально", administrator: "Администратор", playerOne: "Игрок 1", playerTwo: "Игрок 2", password: "Пароль", boundary: "Безопасная граница", safety: "Административные действия контролирует сервер", safetyHelp: "Доступ к участникам, Messenger и тегам проверяется серверными разрешениями и фиксируется в аудите." },
    section: { eyebrow: "Административная панель", create: "Создать", workspace: "Рабочая область", serverData: "Серверные данные · {count}", searchFilters: "Поиск и фильтры раздела", search: "Поиск", roleFilter: "Фильтр по роли", allRoles: "Все роли", player: "Игрок", partner: "Партнёр", marketFilter: "Фильтр по рынку", allMarkets: "Все рынки", turkey: "Турция", azerbaijan: "Азербайджан", apply: "Применить", savedViews: "Сохранённые представления", bulkHelp: "Массовые изменения выполняются только через защищённые серверные команды.", selectRecords: "Выберите записи", status: "Статус", nextStep: "Следующий шаг", openRecord: "Открыть запись", emptyLabel: "Пустое состояние", empty: "Записей пока нет", emptyHelp: "Фильтрам не соответствует ни одна серверная запись.", pagination: "Пагинация раздела", back: "Назад", records: "Записей на странице: {count}", next: "Далее", missing: "Раздел не найден", missingHelp: "Такого административного раздела нет." },
    detail: { edit: "Открыть редактирование", serverData: "Серверные данные", rights: "Права и изменения", control: "Серверный контроль", controlHelp: "Каждая команда повторно проверяет RBAC и сохраняет основание в неизменяемом аудите.", history: "История изменений", historyTitle: "История сохраняется", historyHelp: "Изменения статуса, публикации и решения добавляют новую запись, не перезаписывая прошлое.", operation: "Операционная команда", operationTitle: "Выполнить разрешённое действие", operationHelp: "Основание обязательно, результат фиксируется сервером.", backSection: "Вернуться в раздел «{section}»", noData: "Нет данных", missing: "Сущность не найдена", missingHelp: "Запись отсутствует или недоступна с текущими правами.", backList: "Вернуться к списку" },
    editor: { noData: "Нет данных", unavailable: "Редактирование недоступно", sectionMissing: "Раздел не найден.", mode: "Режим редактирования", create: "Создать: {section}", description: "Изменение создаёт новую серверную версию и сохраняет автора, основание и время.", audit: "RBAC и аудит", draft: "Новый черновик", version: "Новая версия", immutable: "Опубликованная версия не перезаписывается.", back: "Вернуться" },
  },
};

const tr: WorkspaceContent = {
  partner: {
    home: { ...en.partner.home, area: "Partner alanı", title: "Partner çalışma alanı", description: "Partner alanınız rolünüz ve pazarınız için doğrulanmış sunucu verilerini kullanır.", approved: "Erişim onaylandı", pending: "Onay bekliyor", recommended: "Önerilen sonraki adım", openOpportunities: "Çalışma fırsatlarını aç", checkProfile: "Partner profilini kontrol et", noOpportunities: "Şu anda size uygun yeni fırsat yok; kullanılabilir bölümler sunucuyla eşitlendi.", approvalRequired: "Çalışma fırsatları partner erişimi onaylandıktan sonra açılır.", openNext: "Sonraki adımı aç", profileState: "Partner profili durumu", profile: "Partner profili", active: "Aktif", awaitingDecision: "Karar bekliyor", opportunities: "Kullanılabilir fırsatlar", unread: "Okunmamış etkinlikler", serverCalculation: "Sunucu hesabı", currentRank: "Mevcut seviye", assigned: "Atandı", undefined: "Belirlenmedi", noData: "Veri yok", rankHelp: "Seviye, rol ve pazar için yayımlanmış ölçütlere göre belirlenir.", current: "Güncel", confirmedBalance: "Onaylanmış bakiye", serverData: "Sunucu verileri", pointsHelp: "VX Points para değildir; bakiye kayıt defterinden hesaplanır.", cooperation: "İş birliği", accessActive: "Partner erişimi aktif", decisionPending: "Karar bekleniyor", accessHelp: "Durum sunucudaki partner profilinden gelir ve çalışma materyallerine erişimi belirler.", forecasts: "Tahminler", promocodes: "Promosyon kodları", managerMessages: "Yönetici mesajları", statistics: "Özet", activity: "Güncel etkinlik", days: "VX House ile geçen gün", activeTasks: "Aktif görevler", completedTasks: "Tamamlanan görevler", workSections: "Çalışma bölümleri", partnerSpace: "Partner alanı" },
    profile: { ...en.partner.profile, area: "Partner alanı", title: "Profil", description: "Doğrulanmış VX House partner profili bilgileri.", pending: "Onay bekliyor", approved: "Onaylandı", personal: "Kişisel bilgiler", fallback: "VX House partneri", email: "E-posta", market: "Pazar", language: "Dil", created: "Profil oluşturuldu", state: "Erişim durumu", manual: "Manuel onay gerekli", accessApproved: "Partner erişimi onaylandı", pendingHelp: "Profiliniz ve iletişim bilgileriniz doğrulandı. Partner işlevleri VX House ekibinin kararına kadar sınırlı kalır.", approvedHelp: "Yetkiler sunucudaki partner profili tarafından belirlenir." },
    materials: { ...en.partner.materials, eyebrow: "Çalışma içeriği", title: "Materyaller", description: "Rol, pazar ve geçerlilik süresi sunucu tarafından doğrulanan promosyon kodları ve partner koşulları.", count: "{count} materyal", none: "Kullanılabilir materyal yok", empty: "Henüz materyal atanmadı", emptyHelp: "Sistem rolü, pazarı, partner erişim durumunu ve yayın tarihlerini kontrol etti.", back: "Genel bakışa dön" },
    forecasts: { ...en.partner.forecasts, eyebrow: "Analitik materyaller", title: "Tahminler", description: "Yazar, geçerlilik süresi, sürüm geçmişi ve gerekli açıklamayla yayımlanmış materyaller.", count: "{count} kullanılabilir", back: "Genel bakışa dön", none: "Kullanılabilir yayın yok", empty: "Güncel tahmin yok", emptyHelp: "Sistem doğrulanmış rolü, pazarı, kişisel kuralları ve yayın dönemini kontrol eder.", published: "Yayımlandı", author: "Yazar", version: "Sürüm", validUntil: "Geçerlilik sonu" },
    history: { ...en.partner.history, eyebrow: "Şeffaf zaman çizelgesi", title: "İş birliği geçmişi", description: "Partner profili, materyaller ve iletişimdeki doğrulanabilir değişiklikler.", count: "{count} etkinlik", back: "Genel bakışa dön" },
    promocode: { ...en.partner.promocode, activatedMessage: "Promosyon kodu etkinleştirildi ve geçmişe eklendi.", activationError: "Promosyon kodu etkinleştirilemedi.", activated: "Etkinleştirildi", expired: "Süresi doldu", available: "Kullanılabilir", validUntil: "Geçerlilik sonu", role: "Rol", partner: "Partner", player: "Oyuncu", copy: "Promosyon kodunu kopyala", activating: "Etkinleştiriliyor…", activate: "Etkinleştir" },
  },
  admin: {
    overview: { ...en.admin.overview, eyebrow: "Yönetim", title: "VX House çalışma alanı", description: "Üyeler ve kişisel görüşmeler tek bir güvenli arayüzde.", serverData: "Sunucu verileri", users: "Kullanıcılar", registrations: "Yeni kayıtlar", calculated: "Sayfa açıldığında sunucu tarafından hesaplanır.", analytics: "Birinci taraf analitik · 30 gün", funnel: "Erişim hunisi", funnelHelp: "Test hesapları hariç tutulur. Yüzdeler sunucu tarafından hesaplanır.", internalEvents: "Dahili etkinlikler", visitors: "Tekil ziyaretçiler", accessClicks: "Erişim al'a tıklayanlar", registrationStarted: "Kaydı başlatanlar", emailConfirmed: "E-postayı doğrulayanlar", dashboardOpened: "Paneli açanlar", firstView: "İlk doğrulanmış görüntüleme", conversion: "Adım dönüşümü: {value}%", workspace: "Çalışma alanı", areas: "Ana yönetim alanları", areasHelp: "Navigasyonda yalnızca mevcut MVP için gerekli bölümler bulunur.", rbac: "RBAC etkin", open: "Aç", openSection: "Bölümü aç", members: "Üyeler", membersHelp: "Oyuncu ve partner profilleri ile durumları.", membersPurpose: "Üye listesini aç", messengerHelp: "Üyelerle kalıcı kişisel görüşmeler.", messengerPurpose: "Görüşmeyi aç", local: "Yerel test ortamı", demo: "Hazır demo hesapları", demoHelp: "Hesaplar geliştirme sunucusu başladığında otomatik oluşturulur.", localOnly: "Yalnızca yerel", administrator: "Yönetici", playerOne: "Oyuncu 1", playerTwo: "Oyuncu 2", password: "Parola", boundary: "Güvenlik sınırı", safety: "Yönetim işlemleri sunucu tarafından denetlenir", safetyHelp: "Üyelere, Messenger'a ve etiketlere erişim sunucu izinleriyle kontrol edilir ve denetim günlüğüne kaydedilir." },
    section: { ...en.admin.section, eyebrow: "Yönetim", create: "Oluştur", workspace: "Çalışma alanı", serverData: "Sunucu verileri · {count}", searchFilters: "Bölüm araması ve filtreler", search: "Ara", roleFilter: "Role göre filtrele", allRoles: "Tüm roller", player: "Oyuncu", partner: "Partner", marketFilter: "Pazara göre filtrele", allMarkets: "Tüm pazarlar", turkey: "Türkiye", azerbaijan: "Azerbaycan", apply: "Uygula", savedViews: "Kayıtlı görünümler", bulkHelp: "Toplu değişiklikler yalnızca korumalı sunucu komutlarıyla kullanılabilir.", selectRecords: "Kayıtları seç", status: "Durum", nextStep: "Sonraki adım", openRecord: "Kaydı aç", emptyLabel: "Boş durum", empty: "Henüz kayıt yok", emptyHelp: "Seçili filtrelerle eşleşen sunucu kaydı yok.", pagination: "Bölüm sayfalaması", back: "Geri", records: "Bu sayfada {count} kayıt", next: "İleri", missing: "Bölüm bulunamadı", missingHelp: "Bu yönetim bölümü mevcut değil." },
    detail: { ...en.admin.detail, edit: "Düzenlemeyi aç", serverData: "Sunucu verileri", rights: "İzinler ve değişiklikler", control: "Sunucu denetimi", controlHelp: "Her komut RBAC'i yeniden kontrol eder ve gerekçesini değiştirilemez denetim günlüğüne kaydeder.", history: "Değişiklik geçmişi", historyTitle: "Geçmiş korunur", historyHelp: "Durum değişiklikleri, yayınlar ve kararlar geçmişin üzerine yazmadan yeni kayıt ekler.", operation: "İşlem komutu", operationTitle: "İzin verilen işlemi gerçekleştir", operationHelp: "Gerekçe zorunludur ve sonuç sunucu tarafından kaydedilir.", backSection: "{section} bölümüne dön", noData: "Veri yok", missing: "Kayıt bulunamadı", missingHelp: "Kayıt mevcut değil veya geçerli izinlerle kullanılamıyor.", backList: "Listeye dön" },
    editor: { ...en.admin.editor, noData: "Veri yok", unavailable: "Düzenleme kullanılamıyor", sectionMissing: "Bölüm bulunamadı.", mode: "Düzenleme modu", create: "Oluştur: {section}", description: "Değişiklik yeni bir sunucu sürümü oluşturur; yazar, gerekçe ve zaman kaydedilir.", audit: "RBAC ve denetim", draft: "Yeni taslak", version: "Yeni sürüm", immutable: "Yayımlanan sürümün üzerine yazılmaz.", back: "Geri" },
  },
};

const az: WorkspaceContent = {
  partner: {
    home: { ...en.partner.home, area: "Tərəfdaş kabineti", title: "Tərəfdaş iş sahəsi", description: "Tərəfdaş məkanınız rol və bazarınız üçün təsdiqlənmiş server məlumatlarından istifadə edir.", approved: "Giriş təsdiqlənib", pending: "Təsdiq gözlənilir", recommended: "Tövsiyə olunan növbəti addım", openOpportunities: "İş imkanlarını aç", checkProfile: "Tərəfdaş profilini yoxla", noOpportunities: "Hazırda uyğun yeni imkan yoxdur; mövcud bölmələr serverlə sinxronlaşdırılıb.", approvalRequired: "İş imkanları tərəfdaş girişi təsdiqləndikdən sonra açılacaq.", openNext: "Növbəti addımı aç", profileState: "Tərəfdaş profilinin vəziyyəti", profile: "Tərəfdaş profili", active: "Aktiv", awaitingDecision: "Qərar gözlənilir", opportunities: "Mövcud imkanlar", unread: "Oxunmamış hadisələr", serverCalculation: "Server hesablaması", currentRank: "Cari səviyyə", assigned: "Təyin edilib", undefined: "Müəyyən edilməyib", noData: "Məlumat yoxdur", rankHelp: "Səviyyə rol və bazar üçün dərc edilmiş meyarlara əsasən müəyyən edilir.", current: "Aktual", confirmedBalance: "Təsdiqlənmiş balans", serverData: "Server məlumatları", pointsHelp: "VX Points pul deyil; balans reyestr əsasında hesablanır.", cooperation: "Əməkdaşlıq", accessActive: "Tərəfdaş girişi aktivdir", decisionPending: "Qərar gözlənilir", accessHelp: "Status serverdəki tərəfdaş profilindən alınır və iş materiallarına girişi müəyyən edir.", forecasts: "Proqnozlar", promocodes: "Promokodlar", managerMessages: "Menecer mesajları", statistics: "Qısa məlumat", activity: "Cari fəaliyyət", days: "VX House ilə günlər", activeTasks: "Aktiv tapşırıqlar", completedTasks: "Tamamlanmış tapşırıqlar", workSections: "İş bölmələri", partnerSpace: "Tərəfdaş məkanı" },
    profile: { ...en.partner.profile, area: "Tərəfdaş kabineti", title: "Profil", description: "Təsdiqlənmiş VX House tərəfdaş profili məlumatları.", pending: "Təsdiq gözlənilir", approved: "Təsdiqlənib", personal: "Şəxsi məlumatlar", fallback: "VX House tərəfdaşı", email: "E-poçt", market: "Bazar", language: "Dil", created: "Profil yaradılıb", state: "Giriş statusu", manual: "Əl ilə təsdiq tələb olunur", accessApproved: "Tərəfdaş girişi təsdiqlənib", pendingHelp: "Profil və əlaqə məlumatlarınız təsdiqlənib. Tərəfdaş funksiyaları VX House komandasının qərarınadək məhdud qalır.", approvedHelp: "İcazələr serverdəki tərəfdaş profili ilə müəyyən edilir." },
    materials: { ...en.partner.materials, eyebrow: "İş məzmunu", title: "Materiallar", description: "Rol, bazar və etibarlılıq müddəti server tərəfindən yoxlanılan promokodlar və tərəfdaş şərtləri.", count: "{count} material", none: "Mövcud material yoxdur", empty: "Hələ material təyin edilməyib", emptyHelp: "Sistem rol, bazar, tərəfdaş giriş statusu və dərc tarixlərini yoxladı.", back: "Ümumi baxışa qayıt" },
    forecasts: { ...en.partner.forecasts, eyebrow: "Analitik materiallar", title: "Proqnozlar", description: "Müəllif, etibarlılıq müddəti, versiya tarixçəsi və zəruri xəbərdarlıqla dərc olunan materiallar.", count: "{count} mövcuddur", back: "Ümumi baxışa qayıt", none: "Mövcud nəşr yoxdur", empty: "Aktual proqnoz yoxdur", emptyHelp: "Sistem təsdiqlənmiş rol, bazar, şəxsi qaydalar və dərc müddətini yoxlayır.", published: "Dərc edilib", author: "Müəllif", version: "Versiya", validUntil: "Etibarlıdır" },
    history: { ...en.partner.history, eyebrow: "Şəffaf zaman xətti", title: "Əməkdaşlıq tarixçəsi", description: "Tərəfdaş profili, materiallar və ünsiyyətdə yoxlanıla bilən dəyişikliklər.", count: "{count} hadisə", back: "Ümumi baxışa qayıt" },
    promocode: { ...en.partner.promocode, activatedMessage: "Promokod aktivləşdirildi və tarixçəyə əlavə olundu.", activationError: "Promokodu aktivləşdirmək mümkün olmadı.", activated: "Aktivləşdirilib", expired: "Müddəti bitib", available: "Mövcuddur", validUntil: "Etibarlıdır", role: "Rol", partner: "Tərəfdaş", player: "Oyunçu", copy: "Promokodu kopyala", activating: "Aktivləşdirilir…", activate: "Aktivləşdir" },
  },
  admin: {
    overview: { ...en.admin.overview, eyebrow: "İdarəetmə", title: "VX House iş sahəsi", description: "İştirakçılar və şəxsi dialoqlar vahid təhlükəsiz interfeysdə.", serverData: "Server məlumatları", users: "İstifadəçilər", registrations: "Yeni qeydiyyatlar", calculated: "Səhifə açılarkən server tərəfindən hesablanır.", analytics: "Birinci tərəf analitikası · 30 gün", funnel: "Giriş hunisi", funnelHelp: "Test hesabları nəzərə alınmır. Faizlər server tərəfindən hesablanır.", internalEvents: "Daxili hadisələr", visitors: "Unikal ziyarətçilər", accessClicks: "Giriş əldə et düyməsinə basanlar", registrationStarted: "Qeydiyyata başlayanlar", emailConfirmed: "E-poçtu təsdiqləyənlər", dashboardOpened: "Paneli açanlar", firstView: "İlk təsdiqlənmiş baxış", conversion: "Addım konversiyası: {value}%", workspace: "İş sahəsi", areas: "Əsas idarəetmə sahələri", areasHelp: "Naviqasiyada yalnız cari MVP üçün zəruri bölmələr saxlanılıb.", rbac: "RBAC aktivdir", open: "Aç", openSection: "Bölməni aç", members: "İştirakçılar", membersHelp: "Oyunçu və tərəfdaş profilləri və statusları.", membersPurpose: "İştirakçı siyahısını aç", messengerHelp: "İştirakçılarla daimi şəxsi dialoqlar.", messengerPurpose: "Dialoqu aç", local: "Lokal test mühiti", demo: "Hazır demo hesabları", demoHelp: "Hesablar development serveri başladıqda avtomatik yaradılır.", localOnly: "Yalnız lokal", administrator: "Administrator", playerOne: "Oyunçu 1", playerTwo: "Oyunçu 2", password: "Parol", boundary: "Təhlükəsizlik sərhədi", safety: "İdarəetmə əməliyyatları server tərəfindən nəzarət olunur", safetyHelp: "İştirakçılara, Messenger-ə və teqlərə giriş server icazələri ilə yoxlanılır və audit jurnalında qeyd olunur." },
    section: { ...en.admin.section, eyebrow: "İdarəetmə", create: "Yarat", workspace: "İş sahəsi", serverData: "Server məlumatları · {count}", searchFilters: "Bölmə axtarışı və filtrlər", search: "Axtar", roleFilter: "Rola görə filtr", allRoles: "Bütün rollar", player: "Oyunçu", partner: "Tərəfdaş", marketFilter: "Bazara görə filtr", allMarkets: "Bütün bazarlar", turkey: "Türkiyə", azerbaijan: "Azərbaycan", apply: "Tətbiq et", savedViews: "Yadda saxlanmış görünüşlər", bulkHelp: "Kütləvi dəyişikliklər yalnız qorunan server komandaları vasitəsilə mümkündür.", selectRecords: "Qeydləri seç", status: "Status", nextStep: "Növbəti addım", openRecord: "Qeydi aç", emptyLabel: "Boş vəziyyət", empty: "Hələ qeyd yoxdur", emptyHelp: "Seçilmiş filtrlərə uyğun server qeydi yoxdur.", pagination: "Bölmə səhifələnməsi", back: "Geri", records: "Bu səhifədə {count} qeyd", next: "İrəli", missing: "Bölmə tapılmadı", missingHelp: "Bu idarəetmə bölməsi mövcud deyil." },
    detail: { ...en.admin.detail, edit: "Redaktəni aç", serverData: "Server məlumatları", rights: "İcazələr və dəyişikliklər", control: "Server nəzarəti", controlHelp: "Hər komanda RBAC-i yenidən yoxlayır və əsasını dəyişməz audit jurnalına yazır.", history: "Dəyişiklik tarixçəsi", historyTitle: "Tarixçə qorunur", historyHelp: "Status dəyişiklikləri, nəşrlər və qərarlar keçmişi əvəz etmədən yeni qeyd əlavə edir.", operation: "Əməliyyat komandası", operationTitle: "İcazə verilən əməliyyatı yerinə yetir", operationHelp: "Əsaslandırma məcburidir və nəticə server tərəfindən qeyd olunur.", backSection: "{section} bölməsinə qayıt", noData: "Məlumat yoxdur", missing: "Qeyd tapılmadı", missingHelp: "Qeyd mövcud deyil və ya cari icazələrlə əlçatan deyil.", backList: "Siyahıya qayıt" },
    editor: { ...en.admin.editor, noData: "Məlumat yoxdur", unavailable: "Redaktə əlçatan deyil", sectionMissing: "Bölmə tapılmadı.", mode: "Redaktə rejimi", create: "Yarat: {section}", description: "Dəyişiklik yeni server versiyası yaradır və müəllif, əsas və vaxtı qeyd edir.", audit: "RBAC və audit", draft: "Yeni qaralama", version: "Yeni versiya", immutable: "Dərc edilmiş versiya dəyişdirilmir.", back: "Geri" },
  },
};

export const workspaceContent: Readonly<Record<Locale, WorkspaceContent>> = { en, ru, tr, az };
