"use client";

import { useRouter } from "next/navigation";
import { useState } from "react";

import styles from "@/app/dashboard/dashboard.module.css";
import type { AdminRecordView, AdminSectionId, ContentKind } from "@/lib/admin";
import { Button } from "@/components/ui/button";

const kindBySection: Partial<Record<AdminSectionId, ContentKind>> = { opportunities: "OPPORTUNITY", tasks: "TASK", content: "INSTRUCTION", rewards: "REWARD" };

export function AdminCommandForm({ sectionId, record, create = false }: { sectionId: AdminSectionId; record?: AdminRecordView; create?: boolean }) {
  const router = useRouter(); const [pending, setPending] = useState(false); const [message, setMessage] = useState("");
  async function submit(formData: FormData) {
    setPending(true); setMessage("");
    try {
      const rawAction = String(formData.get("action") ?? ""); let command: Record<string, unknown>;
      if (sectionId === "content" && record && !formData.get("kind")) formData.set("kind", record.eyebrow.startsWith("Прогноз") ? "FORECAST" : record.eyebrow.startsWith("Промокод") ? "PROMOCODE" : "INSTRUCTION");
      if (rawAction === "CONTENT_DRAFT") command = { action: rawAction, content: { kind: sectionId === "content" ? formData.get("kind") : kindBySection[sectionId], title: formData.get("title"), description: formData.get("description"), key: formData.get("key") || undefined, role: formData.get("role"), market: formData.get("market"), nextStep: formData.get("nextStep"), instructionVersionId: formData.get("instructionVersionId") || undefined, disclaimer: formData.get("disclaimer") || undefined, validFrom: formData.get("validFrom") || undefined, validUntil: formData.get("validUntil") || undefined, partnerServiceId: formData.get("partnerServiceId") || undefined, code: formData.get("code") || undefined, reason: formData.get("reason") } };
      else if (rawAction === "USER_STATUS") command = { action: rawAction, status: formData.get("status"), reason: formData.get("reason") };
      else if (rawAction === "USER_ROLE") command = { action: rawAction, role: formData.get("role"), reason: formData.get("reason") };
      else if (rawAction === "PARTNER_APPROVAL") command = { action: rawAction, status: formData.get("partnerStatus"), reason: formData.get("reason") };
      else if (rawAction === "MODERATION_DECISION") command = { action: rawAction, decision: formData.get("decision"), reasonCode: formData.get("reasonCode"), reason: formData.get("reason"), comment: formData.get("comment") };
      else if (rawAction === "SUPPORT_ASSIGN") command = { action: rawAction, operatorId: formData.get("operatorId"), reason: formData.get("reason") };
      else if (rawAction === "SUPPORT_REPLY" || rawAction === "SUPPORT_NOTE") command = { action: rawAction, body: formData.get("body") };
      else if (rawAction === "SUPPORT_STATUS") command = { action: rawAction, status: formData.get("supportStatus"), reason: formData.get("reason") };
      else if (rawAction === "APPEAL_DECISION") command = { action: rawAction, appealId: formData.get("appealId"), status: formData.get("appealStatus"), reason: formData.get("reason") };
      else if (rawAction === "ECONOMY_ADJUST") command = { action: rawAction, userId: formData.get("userId"), kind: formData.get("economyKind"), delta: Number(formData.get("delta")), reason: formData.get("reason"), idempotencyKey: crypto.randomUUID() };
      else if (rawAction === "NOTIFY") command = { action: rawAction, userId: formData.get("userId") || undefined, role: formData.get("role") || undefined, market: formData.get("market") || undefined, type: formData.get("type"), title: formData.get("title"), body: formData.get("body"), idempotencyKey: crypto.randomUUID() };
      else command = { action: rawAction, reason: formData.get("reason") };
      const endpoint = create ? `/api/admin/${sectionId}` : `/api/admin/${sectionId}/${record?.id}`;
      const response = await fetch(endpoint, { method: create ? "POST" : "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify(command) }); const payload = await response.json() as { message?: string; id?: string };
      if (!response.ok) throw new Error(payload.message || "Операция не выполнена");
      setMessage("Операция выполнена и записана в аудит."); router.refresh();
      if (create && payload.id) router.replace(`/admin/${sectionId}/${payload.id}`);
    } catch (error) { setMessage(error instanceof Error ? error.message : "Операция не выполнена"); }
    finally { setPending(false); }
  }

  const content = kindBySection[sectionId];
  return <form action={submit} className={styles.adminCommandForm}>
    {content ? <><input type="hidden" name="action" value="CONTENT_DRAFT" />{sectionId === "content" ? <label><span>Тип материала</span><select name="kind" defaultValue={record?.eyebrow.startsWith("Прогноз") ? "FORECAST" : record?.eyebrow.startsWith("Промокод") ? "PROMOCODE" : "INSTRUCTION"} disabled={Boolean(record)}><option value="INSTRUCTION">Инструкция</option><option value="FORECAST">Прогноз</option><option value="PROMOCODE">Промокод</option></select></label> : null}<label><span>Название</span><input name="title" required minLength={3} defaultValue={record?.title ?? ""} /></label><label><span>Описание или содержание</span><textarea name="description" required minLength={3} defaultValue={record?.description ?? ""} /></label><div className={styles.supportFormGrid}><label><span>Роль</span><select name="role" defaultValue="PLAYER"><option value="PLAYER">Игрок</option><option value="PARTNER">Партнёр</option></select></label><label><span>Рынок</span><select name="market" defaultValue="TR"><option value="TR">Турция</option><option value="AZ">Азербайджан</option></select></label></div><label><span>Ключ</span><input name="key" placeholder="Создаётся из названия" /></label><label><span>Следующий шаг</span><input name="nextStep" defaultValue="Открыть опубликованные условия" /></label>{sectionId === "tasks" ? <label><span>ID версии инструкции</span><input name="instructionVersionId" /></label> : null}{sectionId === "content" ? <><label><span>Предупреждение прогноза</span><textarea name="disclaimer" defaultValue="Материал носит аналитический характер и не гарантирует результат или доход." /></label><div className={styles.supportFormGrid}><label><span>Действует с</span><input name="validFrom" type="datetime-local" /></label><label><span>Действует до</span><input name="validUntil" type="datetime-local" /></label></div><label><span>ID партнёрского сервиса для промокода</span><input name="partnerServiceId" /></label>{!record ? <label><span>Код промокода</span><input name="code" autoComplete="off" /></label> : null}</> : null}<Reason /><Button disabled={pending}>{pending ? "Сохраняем…" : "Сохранить новую версию"}</Button></> : null}
    {sectionId === "users" ? <><label><span>Операция</span><select name="action"><option value="USER_STATUS">Изменить статус</option><option value="PARTNER_APPROVAL">Решение по партнёру</option><option value="USER_ROLE">Изменить роль до начала активности</option></select></label><div className={styles.supportFormGrid}><label><span>Статус аккаунта</span><select name="status"><option value="ACTIVE">Активен</option><option value="PENDING">Ожидает</option><option value="SUSPENDED">Заблокирован</option><option value="CLOSED">Закрыт</option></select></label><label><span>Роль</span><select name="role"><option value="PLAYER">Игрок</option><option value="PARTNER">Партнёр</option></select></label><label><span>Решение по партнёру</span><select name="partnerStatus"><option value="ACTIVE">Одобрить</option><option value="SUSPENDED">Приостановить</option><option value="CLOSED">Закрыть</option></select></label></div><Reason /><Button disabled={pending}>{pending ? "Применяем…" : "Применить"}</Button></> : null}
    {sectionId === "reviews" ? <><input type="hidden" name="action" value="MODERATION_DECISION" /><label><span>Решение</span><select name="decision"><option value="CONFIRMED">Подтвердить</option><option value="REJECTED">Отклонить</option><option value="CLARIFICATION_REQUIRED">Запросить уточнение</option><option value="RESUBMISSION_REQUIRED">Запросить повторную отправку</option></select></label><label><span>Код причины</span><input name="reasonCode" required defaultValue="manual-review" /></label><Reason /><label><span>Комментарий пользователю</span><textarea name="comment" /></label><Button disabled={pending}>{pending ? "Сохраняем…" : "Принять решение"}</Button></> : null}
    {sectionId === "support" ? <><label><span>Операция</span><select name="action"><option value="SUPPORT_REPLY">Ответить пользователю</option><option value="SUPPORT_NOTE">Добавить внутреннюю заметку</option><option value="SUPPORT_ASSIGN">Назначить оператора</option><option value="SUPPORT_STATUS">Изменить статус</option><option value="APPEAL_DECISION">Решить апелляцию</option></select></label><label><span>Текст ответа или заметки</span><textarea name="body" /></label><label><span>ID оператора</span><input name="operatorId" /></label><label><span>ID апелляции</span><input name="appealId" /></label><label><span>Статус обращения</span><select name="supportStatus"><option value="ASSIGNED">Назначено</option><option value="WAITING_OPERATOR">Ожидает оператора</option><option value="WAITING_USER">Ожидает пользователя</option><option value="RESOLVED">Решено</option><option value="CLOSED">Закрыто</option></select></label><label><span>Решение апелляции</span><select name="appealStatus"><option value="UPHELD">Удовлетворить</option><option value="PARTIALLY_UPHELD">Удовлетворить частично</option><option value="DENIED">Отклонить</option></select></label><Reason /><Button disabled={pending}>{pending ? "Выполняем…" : "Выполнить операцию"}</Button></> : null}
    {sectionId === "economy" ? <><input type="hidden" name="action" value="ECONOMY_ADJUST" /><label><span>ID пользователя</span><input name="userId" required /></label><div className={styles.supportFormGrid}><label><span>Сущность</span><select name="economyKind"><option value="POINTS">VX Points</option><option value="TRUST">Trust Score</option></select></label><label><span>Корректировка</span><input name="delta" type="number" required /></label></div><Reason /><Button disabled={pending}>{pending ? "Записываем…" : "Создать корректирующую запись"}</Button></> : null}
    {sectionId === "notifications" ? <><input type="hidden" name="action" value="NOTIFY" /><label><span>ID пользователя (необязательно)</span><input name="userId" /></label><div className={styles.supportFormGrid}><label><span>Роль</span><select name="role" defaultValue=""><option value="">Все роли</option><option value="PLAYER">Игрок</option><option value="PARTNER">Партнёр</option></select></label><label><span>Рынок</span><select name="market" defaultValue=""><option value="">Все рынки</option><option value="TR">Турция</option><option value="AZ">Азербайджан</option></select></label></div><label><span>Категория</span><input name="type" required defaultValue="platform-update" /></label><label><span>Заголовок</span><input name="title" required /></label><label><span>Сообщение</span><textarea name="body" required /></label><Button disabled={pending}>{pending ? "Отправляем…" : "Создать серверные уведомления"}</Button></> : null}
    {message ? <p role="status" className={styles.supportFormDisabled}>{message}</p> : null}
  </form>;
}

function Reason() { return <label><span>Обязательное основание</span><textarea name="reason" required minLength={3} /></label>; }

export function AdminPublicationActions({ sectionId, record }: { sectionId: AdminSectionId; record: AdminRecordView }) {
  const router = useRouter(); const [message, setMessage] = useState("");
  async function run(action: "CONTENT_PUBLISH" | "CONTENT_ARCHIVE") { const reason = window.prompt("Укажите основание действия"); if (!reason) return; const response = await fetch(`/api/admin/${sectionId}/${record.id}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ action, reason }) }); const result = await response.json() as { message?: string }; setMessage(response.ok ? "Статус обновлён и записан в аудит." : result.message || "Операция не выполнена"); if (response.ok) router.refresh(); }
  return <div className={styles.adminPublicationActions}><Button type="button" onClick={() => run("CONTENT_PUBLISH")}>Опубликовать</Button><Button type="button" variant="outline" onClick={() => run("CONTENT_ARCHIVE")}>Архивировать</Button>{message ? <p role="status">{message}</p> : null}</div>;
}
